### ISSUE TITLE
Wrong GPS centering

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#116]
When I touch GPS button, center the only one coordinates - 23.663, 55.191 (Arab Emirates?)

Sony xperia tablet z1
Android 5.1
QField version 0.9.8

**Comment by m-kuhn** [comment]
Thank you for reporting this @giedrioks26 

It would be great if you could add some more information that will help to understand what exactly the problem is and how to fix it. Of particular interest here:

* Which it the CRS of your project?
* What would be expected results at your position, what is the real result?
* Is this a new issue 

https://github.com/opengisch/QField/blob/master/.github/ISSUE_TEMPLATE.md contains a list of things that are often good to add.

**Comment by giedrioks26** [comment]
my project CRS 3346
not show my GPS location only snap and show coordinate - 23.663, 55.191
to 0.9.7 version works fine. it starts from 0.9.8

**Comment by giedrioks26** [comment]
och sorry ... I tried to reinstall qfield 0.9.8. Now it works fine.
