### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by chanteclair12** [opengisch/QField#1201]
Hello everybody,
I am a new user of QField.
I work on Windows 10, Qgis 3.4.5, plugin QField Sync 3.2.1 and PGSQL 9.6.
I have a question about the use of QField : i don't understand what are the checkbox in front of each attribute to enter. I do not find any help about this.
Thanks.

**Comment by VxTedxV** [comment]
All is detailed on Qfield website in documentation : [https://qfield.org/docs/en/user-guide/index.html](https://qfield.org/docs/en/user-guide/index.html)

> The checkboxes at the right of every attribute allow for remembering each attribute individually. The next time you will add a feature on the same layer, these attributes will be already pre-filled.

**Comment by chanteclair12** [comment]
Thanks for your answer, it is a part that i missed in the guide.
Have a good day.
Regards.

**Comment by flotschi2004** [comment]
Is it possible to deactivate these checkboxes in the QField view?

**Comment by signedav** [comment]
Not yet. Would you appreciate to be able to deactivate it?

**Comment by flotschi2004** [comment]
I think it can be confusing to users and it would help to create as simple projects as possible

**Comment by signedav** [comment]
You are right. On the other hand, when it's hidden per default, the user does not even know about this possibility. It's always hard to find the balance between having an option visible per default (so the users knows about it and can make use of it) and have it hidden and it does not mind users that don't use it anyway.

But since our widgets get more and more powerful and we have to care about the space in the form, it would anyway make sense to have a thought about it. What is your opinion about it @nirvn ?

**Comment by nirvn** [comment]
@signedav , those checkboxes have always been "weak" UI/UX wise as there is no label or identification on-sreen of what they do. Yet, we obviously can't add a label for each of those check boxes.

If we could find a nice icon that does a good job at representing the concept of "remembered value", I'd go for that.

**Comment by nirvn** [comment]
@signedav , one alternative, we could seize this as the moment we introduce "first seen help balloons" which could pop on the screen the first time users see a feature addition form. We can make this generic and re-use it in other places.

**Comment by signedav** [comment]
First seen help balloons is anyway we might need sooner or later.
But even with balloons it might be cool for the user to disable their visibility (or enable in case they would be hidden per default).

**Comment by nirvn** [comment]
Yeah. I'm not feeling super great at the idea of adding a setting in the settings panel. Maybe a toggle that's part of the feature addition form itself ... [ show remember value check boxes ____ (o _) ]

It could sit at the bottom of the form.

**Comment by signedav** [comment]
Mhm this is a nice idea. But not completely happy. Since we have in the three-dot menu "actions" and not "settings" ATM. Anyway, this is a good idea. Let's keep these ideas in mind.

**Comment by flotschi2004** [comment]
Perhaps this question also fits in here: I've defined a boolean attribute and get two checkboxes in QField but but no label/identification which represents yes and which no - can I introduce somehow a label for the checkboxes?

**Comment by Sergo993108** [comment]
Guys, hello everyone
@nirvn @signedav 
Its good that I found this thread because as i can see someone already asked this question. Is it possible to somehow hide or disable this checkbox that sits next to the fields? I would like to disable it because this field where i will enter data they will be always unique because it is comment field that user will enter so it will be always different. That is why i want to hide or disable this checkbox in order not to confuse or not to breakdown the idea of this field.

**Comment by elliec** [comment]
@nirvn was there any progress on this? we are assessing Qfield for mine action activities. Qfield is great, but our forms can have quite a lot of fields. The checkboxes make what is already a busy form really cluttered and hard to navigate, and we would never use them. We havent tested in the field yet but from experience I imagine they could also be easily accidentally checked. I had to google a fair bit just to work out what they were. If there is a toggle somewhere to disable them it would make the form so much more useable! Thanks

**Comment by nirvn** [comment]
@elliec , it's an improvement we understand is needed, but it'll probably not happen without sponsorship. If you are interested in supporting this effort, please reach out to info@opengis.ch.
