### ISSUE TITLE
Question : IOS ?

### ISSUE THREAD

**Issue by ponceta** [opengisch/QField#122]
In Switzerland, IOS is well widespread in terms of mobile devices.

What would be the prerequisite for an IOS translation of this kind of project?

Since QT is also on IOS it would be possible right? (I did not mean easy ;) )

In Pully we started a few years ago on IOS devices like iPads to navigate on field using webgis adding QFIELD on these devices would be great for network services.

**Comment by pcav** [comment]
I also received similar requests. There migh be a commercial potential.

**Comment by m-kuhn** [comment]
The main challenges are not technical but related to licensing and publishing open source apps in the app store. We already were in contact with a lawyer and are exploring the possibilities.

Good to know there is interest!

**Comment by ponceta** [comment]
Ok, nice! @m-kuhn keep us in touch whenever there are some evolutions! :+1:

**Comment by ponceta** [comment]
@m-kuhn any news here?

**Comment by ponceta** [comment]
@m-kuhn Anything we can do to help here?

**Comment by m-kuhn** [comment]
@mbernasocchi evaluated possibilities a couple of months back

**Comment by mbernasocchi** [comment]
In fact, there is a doable workaround for the license part. we would now need to start looking into the technical part which will need some time commitment. The current status for us is that as soon as we get enough economic support we'd like to dive into this.

**Comment by ponceta** [comment]
@mbernasocchi, in "doable workaround" and "start looking into the technical part", this is not very engaging and not very reassuring in terms of economical perspective.

But if you consider swiss mobile stats, there are more than 50% IOS devices yet.
http://gs.statcounter.com/os-market-share/mobile/switzerland

Is android more open to opensource developpements than apple?
If QFIELD has to be developped twice when integrating on IOS, that's maybe not the goal targeted.

**Comment by M-Rick** [comment]
Maybe this can interest you.
Input is a QGIST based and open source application for both iOS and Android devices.
It has been made by Lutraconsulting, the team packaging the new QGIS versions for MacOS.
https://inputapp.io

**Comment by mbernasocchi** [comment]
@M-Rick we are well aware of Input, as it originally was forked out of QField. and share lots of code and all the background library build scripts.
@ponceta having an iOS version of QField is now much higher on our priority list. If this will be in the iOS AppStore is still a completely different question since the licensing problem still exists. But alternatives to the AppStore do exist. if anybody is interested in participating sponsoring such feature don't hesitate to contact us.

**Comment by M-Rick** [comment]
> @M-Rick we are well aware of Input, as it originally was forked out of QField. and share lots of code and all the background library build scripts.
> @ponceta having an iOS version of QField is now much higher on our priority list. If this will be in the iOS AppStore is still a completely different question since the licensing problem still exists. But alternatives to the AppStore do exist. if anybody is interested in participating sponsoring such feature don't hesitate to contact us.

How will you distribute a software outside the App Store? There is no way to install it despite using the developper's TestFlight application. No one uses jailbreak that even became almost impossible nowadays. Plus it used to bring quite a lot of troubles.
I don't understand why there is a licensing problem. Qfield for Android is in GPL v2. Signal, the open source chatting application is in GPL v3 and its source code open as well and perfectly available on GitHub for iOS.
https://github.com/signalapp/Signal-iOS
VLC for iOS is released under MPL v2 and GPL v2 and freely available there
https://www.videolan.org/vlc/download-ios.html
And the iOS license can be different than the Android one since the source code will be different anyway.

**Comment by M-Rick** [comment]
Did you give a look at this?
It could be a good alternative?

> An Open Source framework to create native mobile (iOS, Android) and Desktop (Windows, macOS, Linux Intel and ARM) applications in Java using the iOS API.

https://crossmobile.org

**Comment by jokd** [comment]
Hi
Any progress on this? Saw a presentation late last year where there was an QField on iOS teaser, will this be published in App Store in near future or available elsewhere?

**Comment by nirvn** [comment]
Answer: https://qfield.org/docs/install/
