### ISSUE TITLE
Cannot add a child element in a nested relation

### ISSUE THREAD

**Issue by 3nids** [opengisch/QField#1283]
If you have layer A <- layer B <- layer C (A referenced by B referenced by C).

Open feature form of A you can a add a referencing feature in B => expected

Now, if you either create B or open the form of an existing B (still from A), you can add a referencing feature in C => not expected

**Comment by signedav** [comment]
Wen open the form of an existing B, the form of C is displayed?

**Comment by 3nids** [comment]
yes, if C already has features referencing B, they are listed and you can open their form (C) in a new window.
You cannot edit them obviously.

So I guess the trick is that the embedded form should be in edit mode when you open it from an editable form.
Makes sense?
Is this a tricky thing?

**Comment by signedav** [comment]
Ah I get it. When having a relation editor in an item of a relation editor... hm... I remember something like it's on purpose to avoid troubles. But I have to check again. Coming back to you...

**Comment by signedav** [comment]
I checked my notes from back then. We decided to disable the nested relation editors with this https://github.com/opengisch/QField/blob/master/src/qml/FeatureForm.qml#L362 because of "random crashes". I didn't investigated in it, since it has not been requested to use nested relation editors. So to your question: It's easy to enable, but it might request some effort in testing and finding the reason for the crashes (in case they persist).
