### ISSUE TITLE
Support for staking out points

### ISSUE THREAD

**Issue by Cantalou15** [opengisch/QField#1366]
On the fields, we often need to go back to some places we went month or years ago. 
It would be great if Qfield could guide us to the point we need to reach. Hiking Apps can do that. But the accuracy is not good to work with a RTK centimeter positionning.

The aim is: To select a point to reach. Have the distance, the line to the point and the direction with automatic zoom management when approaching the point.

### How it works on other Apps

https://docs.emlid.com/reachrs2/common/reachview/survey/#staking-out-points

![Reach RS+](https://user-images.githubusercontent.com/12166686/96684901-a3358c00-137c-11eb-8d08-1af86a8f40f3.gif)

**QField version:** Enhancement for future QField release

**Comment by 9ls1** [comment]
Any progress regarding the possibility to stake out points? Or even better in some cases: stake out a vertex on a polygon  - not having to make a  point file based on the polygon file in advance. 
Looks like **Input** has the possibility already in their latest release 1.3.0 [https://merginmaps.com/docs/field/stake-out/](url)

**Comment by nirvn** [comment]
QField 2.1 (ETA May 2022) will have navigation support with auto map canvas panning /zooming of navigation destination & device location.

You can builds here: https://github.com/opengisch/QField/pull/2636

This brings QField halfway to staking. Hope that'll fulfill some of your needs. If anyone is interested in supporting the last few miles needed (namely a high precision view when getting really close to the staked location), feel free to reach out.

**Comment by Marwe** [comment]
@nirvn Great to see this feature in the QField dev version!

While testing it I found a small issue: I would like to navigate to a feature, currently I was only able to navigate to a (tapped) point (set coordinates as destination). This may be pretty near, but not exactly on the point/feature itself. Due to the display it is possible to zoom in and see details, but if you don't zoom, you may miss that the target point is a bit off.

In the screenshots you see my targeting being a bit off to the point, even if it may be on a tiny scale (RTK used), you can see current position, target coordinate and feature at different locations.
However, with the circle around the position you can estimate that you are at the location within the measurement accuracy.

![1024-2276](https://user-images.githubusercontent.com/2165004/161864270-6fd33528-afd9-40d9-809a-e5b0328e7f62.png)
![1024-2277](https://user-images.githubusercontent.com/2165004/161864261-bd72dc6f-3fd7-42ba-903c-75fc4be3dbcc.png)

**Comment by nirvn** [comment]
@Marwe , glad this got you excited :)

In addition to long tapping the canvas to set a destination, you actually can use a feature as destination:
![Screenshot_20220406-070712](https://user-images.githubusercontent.com/1728657/161870919-2be57310-44f8-4b57-b9a2-ee9dfa819e78.jpg)

A third way to set a destination is to type an X,Y coordinate in the search bar and type on the flag icon:
![Screenshot_20220406-070637](https://user-images.githubusercontent.com/1728657/161871018-9a2a1a94-20f2-41ef-9424-7e8aacb517af.jpg)

**Comment by nirvn** [comment]
Oh sorry @Marwe , I forgot to mention a 4th way, which actually might also help your workflow. An alternative method to set a destination to match a feature geometry (point or otherwise) is to search for features using the search bar and use the new flag icon to set a feature in the search result as destination:
![Screenshot_20220406-071904](https://user-images.githubusercontent.com/1728657/161871741-d14a9801-42ff-4c18-8001-db58b249602b.jpg)

The feature search is triggered with a minimum of 3 characters typed, so you could name points eg "poi-01", "poi-02", etc.

**Comment by Marwe** [comment]
@nirvn thanks for the heads up, I did not select the point, and therefore had the wrong 3-dot context menu...

One more thing: If I select a polygon, I might be interested to go to its vertexes, currently a point within the polygon is the target coordinate (centroid is a kind of virtual point). Would it be possible to select a specific vertex of a polygon (for lines it may make sense, too)? I could not select a vertex, in edit mode they are at least shown.

It might even be a feature to always select the nearest vertex to current position as target, then you can walk along the line/border and the nearest vertex just 'snaps'. Though it might be weirdly hopping with large positional errors vs. small features...

**Comment by nirvn** [comment]
@Marwe , those are good suggestions which we should definitively take into account when we get funding for additional work specifically on stake out mode.

**Comment by 9ls1** [comment]
This is really good news. How may one support/contribute with funding specific to this stake out mode development? Will you make a campaigne?

**Comment by m-kuhn** [comment]
Please shoot us a mail to info at opengis dot ch

**Comment by 9ls1** [comment]
I have sent you several emails to your info at opengis dot ch address, but can't see that I have received any replies?

**Comment by m-kuhn** [comment]
Thanks.
You should have received a reply now, sorry for the waiting time.

**Comment by m-kuhn** [comment]
This is implemented in https://github.com/opengisch/QField/releases/tag/v2.2.2
