### ISSUE TITLE
QField closes by closing the Identify window

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#138]
When I try to close the identify results window, it does not close or close QField

Action from which this happens:
1. Press the screen to identify the object. Identity window pops up. Press the "back" button. The identification window closes. Everything is fine here.
<img src="http://i.imgur.com/iKDYID4.jpg" >

2. Touch screen to identify the object. Identity window pops up. Press the grid and mark the layer or go to the next layer. I close the layers window. Press the "back" button to hide the identification window. QField closes.
<img src="http://i.imgur.com/VxyABl9.jpg" >

**QField version:** 0.10

**Comment by tveinot** [comment]
+1 Having same issue as well on Samsung Galaxy Tab E 9 inch.

**Comment by saemiw** [comment]
Yes this behaviour has also caused quite some confusion for our users. It would be nice to have an button (x) to close the identify window instead of using the return button. How about this:
![prasentation4](https://user-images.githubusercontent.com/20398621/31996628-78b230c8-b989-11e7-8596-9633409f322d.jpg)
