### ISSUE TITLE
Qfield documentation

### ISSUE THREAD

**Issue by mixedbredie** [opengisch/QField#14]
Is the Qfield documentation available online somewhere?

**Comment by m-kuhn** [comment]
Documentation does not yet exist since we want to focus on still missing base functionality first.
If there is interest for a community driven documentation approach, we will be happy to put the required infrastructure (github project similar to [QGIS-Documentation](https://github.com/qgis/QGIS-Documentation)) in place.

**Comment by tudorbarascu** [comment]
@m-kuhn Hi, whenever you want to start the documentation process, I would like to help.

**Comment by m-kuhn** [comment]
Infrastructure has just been put in place.

https://github.com/opengisch/QField-docs

http://opengisch.github.io/QField-docs/

pull requests are welcome.
