### ISSUE TITLE
Autoincremental ID doesn't working

### ISSUE THREAD

**Issue by Cucumerlu** [opengisch/QField#1627]
Hi,
I'm working with a point shp and I'd like a new incremental ID when I create a new point. This process seems working in QGIS but not in QFIELD ( it works only if an object  (a point with  numeric ID) does already exist.

**Comment by she-weeds** [comment]
What expression are you using for this? I haven't had any trouble with this - I use coalesce(maximum("idfield"),0)+1 to start incrementing from the highest value in the column idfield, or if there are no features, start from 1.

**Comment by Cucumerlu** [comment]
Thank you!!The problem is: with that expression the "idfield" change if I modify a value in any field of the object.
For example:
POINT 1:
idfield: 1
value: 128

if I change value in POINT 1, the idfield changes too.

At the moment I use the expresson IF ("id" is NULL,maximum("id") + 1, "id") but it want a "first object" to start the count and there are some problem in visualisation in QFIELD (if i already have id 1, 2 and 3, when I enter in edit mode I see id 3 instead id 4)
Can you help me?

**Comment by she-weeds** [comment]
Make sure "apply default expression upon update" is *not* enabled in the qgis attribute form, as you only want the number to auto increment when you create the feature, not every time you update it.

And your expression won't work for the first feature because if you have no features at all and therefore no "id" values, maximum("id") returns NULL and NULL +1 is still NULL. That is why you use coalesce(maximum("id"),0) which returns 0 if maximum("id") is NULL, then increment by 1.

**Comment by Cucumerlu** [comment]
Thank you very much!
You have solved my problem

Federico

Il giorno dom 31 gen 2021 alle ore 20:57 she-weeds <notifications@github.com>
ha scritto:
