### ISSUE TITLE
Permission denied while running ./scripts/build.sh

### ISSUE THREAD

**Issue by connectionlink** [opengisch/QField#1706]
output:

[user@localhost QField]# ./scripts/build.sh
bash: /usr/src/qfield/scripts/docker-build-wrapper.sh: Permission denied

**Comment by signedav** [comment]
Maybe you need root privileges for docker commands. Try `sudo ./scripts/build.sh`.

**Comment by connectionlink** [comment]
Yes the command was run with sudo. I've also double checked the docker installation?

**Comment by m-kuhn** [comment]
I assume it's related to selinux. https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

Proper solution:

Adjust `scripts/builds.h` and change volumes to be mounted with `Z`

If that works for you, a pull request to adjust the script would be appreciated.

Otherwise a simpler but less clean approach is:

```
su -c "setenforce 0"
```

**Comment by connectionlink** [comment]
I think you found it! The build progress up to downloading the Gradle wrapper. All should be good, if I recall correctly the last time it hung up before that, but I cannot proceed all the way right now. Currently out of data. 

Will post back an update in several days.

Many thanks,
