### ISSUE TITLE
Issue with the map theme on qfield

### ISSUE THREAD

**Issue by zakigates** [opengisch/QField#175]
I have an issue, I created two presets on qgis and they work very well when switching from one to another, yet on qfield and when I choose a map theme some layers are not displayed especially those that  have a ruled style. I'm blocked at this step. Please if you have any Idea about how to fix this issue tell me.

**Comment by koenigherford** [comment]
I've got the same issue in my projects. 

It seems, that it can be fixed by the following steps 
1) open the project in qgis-desktop
2) Loop manually trough every MapTheme and
   2.1) check/uncheck the visibility of every rule of every layer
   2.2) replace the MapThemeSetting with (after modifing the checkboxes as described in 2))
3) Save the offline-project and copy it to the mobile device

This is a very time-consuming approach -especially if you have got several map themes with several layers and a lot of rules.

Hopefully the map-theme-settings will be transferred unchanged from qgis3-projects

**Comment by koenigherford** [comment]
@zakigates : how to check / uncheck all rules at once by a phyton-script see: [https://gis.stackexchange.com/questions/261090/checking-unchecking-rule-visibility-of-layers-at-once-in-qgis] - Thanks to Joseph

**Comment by signedav** [comment]
Anyone knows what is the status with QGIS 3?

**Comment by 3nids** [comment]
@m-kuhn could it be an issue of the duplication of layer? i.e. the rule gets a different id and thus the theme has invalid info?

**Comment by m-kuhn** [comment]
No idea.

**Comment by saemiw** [comment]
Could e related to this issue: https://github.com/opengisch/QField/issues/234

**Comment by suricactus** [comment]
Is this still an issue?

**Comment by soester** [comment]
i think this can ce closed...
