### ISSUE TITLE
QField for windows re-pairing bluetooth failed

### ISSUE THREAD

**Issue by dingausmwald** [opengisch/QField#1866]
Couldnt get external bluetooth rtk (simplertk2b) to work with windows 10 beta on laptop (with or without LEFEBURE NTRIP Client). Qgis log says re-pairing bluetooth failed, 2 times. Scanning works. Just connecting doenst. Ntrip has connection with rtk. Works with qfield for android. Started as admin doesnt help. Seems like qfield cant command the bluetooth adapter to repair. Why repair? To make some handshakes with the rtk system i think. Or am i missing smth?

**Comment by signedav** [comment]
You are trying to connect your rtk to a QField running on Windows?

The re-pairing is done for every platform except Android. Means for Linux (what we use mainly for development) at the moment this feature has been developed. This because Linux requested it (un-pair and pair again before it was able to connect to the device).

It's pretty good possible that Windows (and maybe iOS) does not need the re-pairing. So we could exclude it from the Windows/iOS workflow here as well:
https://github.com/opengisch/QField/blob/master/src/core/bluetoothreceiver.cpp#L69-L71

**Comment by dingausmwald** [comment]
Yes, im trying. The repairing doesnt work on windows in the first place, like its stuck. The console wont go further and qfield gui is responsive but the loading ring at the device dialog in positioning tab (settings) keeps spinning forever and the menue is greyed out. I could test the behaviour on windows for you if needed. Turning it off seems the easy way while hoping its not needed. Devices i have here are a i7 laptop and windows surface pro 7 to test it.
Anyway, awesome work on qfield. hope qgis gets that stable that fast.

**Comment by m-kuhn** [comment]
It was a random commit, unverified if it changed anything
@dingausmwald can you try with [the latest build](https://nightly.link/opengisch/QField/workflows/windows/master/QField-dev-Release.zip)?
