### ISSUE TITLE
Sort features on features list

### ISSUE THREAD

**Issue by balogh89** [opengisch/QField#1897]
Is there a way to sort features on features list? It seems to me, there is a random order, even if I set display and sort values in QGIS before.

**Comment by lp-dj** [comment]
I think currently the features are not random but sorted by their fid, right? But anyway: I agree with you @balogh89 that this sorting is rarely useful in the field.

I think at the latest now that it is possible to select features by symbol category thanks to #3261 , your enhancement requested here would make sense.

From my point of view the next logical step would be to be able to sort or filter the possibly very long feature list.

For example, I would find it very handy to be able to sort the selected features by distance from my own location or to filter them within a buffer around my own location.

In my mind, implementing a default sort by display name instead of fid should be the easiest way, right? That would probably leave much else up to the user's configuration.

Haven't tried it yet, but I think using the @gnss_coordinate variable and the distance function it should be no problem to set the distance of a feature to your own location as the display name?

**Comment by nirvn** [comment]
Implemented here: https://github.com/opengisch/QField/pull/4192

**Comment by nirvn** [comment]
Implemented.
