### ISSUE TITLE
Problem entering decimals in spatialite layers

### ISSUE THREAD

**Issue by soester** [opengisch/QField#197]
QField doesn't offer decimal point when entering Data in a Field with format 'DOUBLE'.

### Reproduction Steps:

1. Create Offline Project from Postgres
2. Fieldtype in Sqlite is  'DOUBLE'
3. Enter Data in QField
4. Data entry with decimal point not possible (Android doesn't offer decimal point in keypad).

### Expected behavior:

Decimal Point should be displayed / usable

### Observed behavior:

No decimal Point displayed / usable

**QField version:** 0.10.4

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

We had no Problems with this in 0.10.3 (was fixed around 0.10.2).
Might be related to #173 and its related fix?

**Comment by m-kuhn** [comment]
What do "length" and "precision" indicate in the layer properties -> fields tab?

**Comment by soester** [comment]
Ok. It is a QField-Sync / Offline Project problem:

**Postgres:**
Type: DOUBLE
Type name: numeric
Length: 6
Precision: 1

**Offline-Project (Sqlite):**
Type: double
Type name: DOUBLE
Length: 0
Precision: 0

Where should issues about QField-Sync / Offline Project be posted?

**Comment by m-kuhn** [comment]
It's not a QFieldSync problem, it's in QField, it should apparently also take the type into consideration (and not only the precision)

**Comment by m-kuhn** [comment]
@soester do you have a project somewhere close which you could attach here to investigate the problem?

**Comment by fahrwegdienste** [comment]
I detected the same issue which worked fine in QField 0.10.1. I tried to set length and precision for a new field of type double. I am working with an offline gpkg. 
Apparently, when saving the project file, QGIS does not save these settings. When opening the project file again and having a look into  the fields, they just show 0 for length and precision! QGIS v. 2.18.14. 

Would be nice if QField only checks the type so that this QGIS issue can be ignored?!

![image](https://user-images.githubusercontent.com/33343856/35919864-8bc873c2-0c16-11e8-9428-f6e6b526b65a.png)

**Comment by saemiw** [comment]
You encountered this problem with QField 0.10.8_5?

**Comment by fahrwegdienste** [comment]
Yes. And also in version 0.10.4

**Comment by gaby-h** [comment]
I can confirm the problem: in QGIS 2.18.15 the precision and length-information ist lost as soon as I close QGIS.
After saving:
![grafik](https://user-images.githubusercontent.com/33145785/36024876-6b835358-0d91-11e8-9464-93b1da9ad74a.png)
After reopening QGIS:
![grafik](https://user-images.githubusercontent.com/33145785/36025019-eaa1b882-0d91-11e8-9a30-f512465bf3f8.png)
An after reopening, its also possible to enter longer decimal numbers (precision > 1 as defined)!!
![grafik](https://user-images.githubusercontent.com/33145785/36025109-2bfc9342-0d92-11e8-8b2e-a503345a7517.png)
![grafik](https://user-images.githubusercontent.com/33145785/36025122-3d567cac-0d92-11e8-9ab9-0722358b19ed.png)
But as long as not closed QGIS after defining the column, he respects the precision length (in the example above the column "double2"

I confirm also, that entering decimal numbers isn't possible on the tablet (QField 0.10.8_5; Device: Samsung Galaxy Tab Active2).

**Comment by saemiw** [comment]
My comment is probably the same as the one from @gaby-h. I got the following feedback from our fieldworkers. 

> For numeric input, there is no longer an option for typing in . , or - the . And, aren't such a huge issue , but the - is a problem because we have minus temperatures sometimes, and it means I will have to change the input type of many previously numeric fields to text, which I guess will cause syncing problems.

It seems that qfield 0.9.10 cannot accept/enter negativ and comma values when defined correcty as numeric/double/real what ever in QGIS. This is pretty annoying. Work around is of course to save as text...but that doesn't seem a good solution to me. If it is numeric at the moment QField only allows to enter positiv integer values (the popup doesn't offer comma or - sign). This was possible in earlier versions because the whole keypad was offered to enter data

**Comment by saemiw** [comment]
If you do have time to look at this issue I'd be very glad. This is a quite important issue for us - because projects from 2017 cannot be continued when using the latest verson of QField (which is thanks to your excellent werk much more powerful than previous versions!!!). . If there is not software solution, we'll have to change many fields in existing projects from currently _numeric_ to _text_. As many field projects are about to start (some already started) it would be nice to have a solution more or less quickly. Sorry for stressing...

**Comment by m-kuhn** [comment]
@saemiw we'll discuss and let you know later today.

**Comment by saemiw** [comment]
I have Android-Version 5.1.1 I'll send the two projcts through wetransfer to info@opengis.ch (in a few seconds)

**Comment by djes** [comment]
This bug seems to have reappeared in QGIS 3.0.2...

**Comment by m-kuhn** [comment]
I'm surprised to hear this is related to a QGIS version. The fix in here was done on QField side.

**Comment by djes** [comment]
Was just googling for this bug and found this thread...

**Comment by m-kuhn** [comment]
Nevermind, please also leave a link to the issue report here. Thanks !

**Comment by djes** [comment]
Thank you ! I found two posts about this bug, the latest one being there : https://issues.qgis.org/issues/18963
