### ISSUE TITLE
Filter "is_selected()" for atlas print does not work

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#2076]
To enable the field workers to print a PDF from QField, i created a print layout. A virtual column ("Selected") with the expression "is_selected()" was introduced and the atlas option in the layout form is set to Filter by: "Selected=1", so only selected features will be printed (with QGIS atlas enabled). In QGIS this works fine, QField seems not to evaluate the expression (if i select multiple features via "toggle feature selection" none of them shows selected=1), therefore the atlas print does not work. 

Is there another way to get  multiple printed pages with the same layout out of QField? If i create a print layout without atlas function (basically a better screenshot) it will always export it as "Documents/Formular.pdf", ergo overwriting the previous export.

QField 1.9.6, QGIS 3.16.9

**Comment by signedav** [comment]
Yes, it's possible to print an atlas. For the naming you can use expressions in your layout's settings:
 
![atlasnaming](https://user-images.githubusercontent.com/28384354/129159215-8fbfbbdf-826a-4253-81b1-17b5ed16e55e.png)

The filter "is_selected()" does not work in QField since the way of selecting features is a different one on the mobile UX. But it should be well possible by just selecting them (with the mentioned "toggle feature selection" function) and then use "Print Atlas Feature(s) to PDF"

See for more information about this feature https://github.com/opengisch/QField/pull/1731

**Comment by meyerlor** [comment]
ah well, that solved it - thank you!

**Comment by GlaDal** [comment]
Hi signedav,

According to your message from the Aug 12, 2021, it seems possible to define the name of a pdf with an expression. On my side, it doesn't work (with version 2.5.6). This functionality is not more supported or I'm doing wrong somewhere ?
Thanks by advance.

**Comment by signedav** [comment]
Can you provide more information. What is your pdf named like?

**Comment by GlaDal** [comment]
I tried an expression querying three differents fields. I didn't work.
I tried something basic with only $id. It doesn't work.
![image](https://user-images.githubusercontent.com/7015197/206399399-a27a76dd-df73-41c7-b014-1b8c5cd6ff2e.png)
The name's issue from Qfield remains : 'A3_PAYSAGE-20221208_093751' ('A3_PAYSAGE' is the name of my layout. The rest is obviously the date and hour.
Thanks

**Comment by GlaDal** [comment]
I can't reproduce the problem. I bugged. Sorry for the trouble. 
It works ! Thanks.
