### ISSUE TITLE
Samsung  s6 issue

### ISSUE THREAD

**Issue by Sorinpop97** [opengisch/QField#2110]
I am having issues with the app on samsung gaxy s6. When I try to access the local files, to access a new project the app shows a white screen and then takes me back to the main page.

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 2.0.2 Beta 3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No, only with demos

**Comment by nirvn** [comment]
@Sorinpop97 , I suspect you are being hit by a known issue with older samsung devices whereas QField will crash when sending network requests. In your case, if I understand your issue probably, you see a crash when opening local datasets on your device. When doing so, an XYZ openstreetmap layer is added and causes the crash due to network request to fetch tiles.

While we understand the cause of the crash, a fix is quite complex and will likely not come without some form of sponsorship. Moving to a newer device would also fix this issue.

@m-kuhn , do you remember which open issue is used to track this specific samsung crasher?

**Comment by suricactus** [comment]
Most of the discussion was here https://github.com/opengisch/QField/issues/1327

**Comment by m-kuhn** [comment]
Could you try with the apk here:
https://github.com/opengisch/QField/pull/2366#issuecomment-1000813526
Thanks
