### ISSUE TITLE
Data not up to date when accessed via usb

### ISSUE THREAD

**Issue by Remmug** [opengisch/QField#2222]
We are using Qfield 1.9.6 with an Android 7.0 tablet to collect data, but sometime the data collected disappear from the tablet. We use QField, collect the data on the field, then plug the tablet into the computer and copy paste the file that are in the Qfield folder of the tablet.

It's like the data has never been saved in the tablet so I want to know if a specific thing or behaviour can produce this problem.

. This problem occur since atleast 1years. 
. This problem occur no matter what the project is. 
. This problem don't occur every time. 
. I don't know if this problem occured exclusively on this Qfield version. 

I guess the problem come from us because I didn't find any similar problem in the Issues topics.

- Is a tablet that run out of battery with the project open in edit mode could delete all the new modifications ?
- Is a tablet shut of with the project open in edit mode could delete all the new modifications ?
- Is a tablet with no available memory could not save the new modifications despite letting us do it ?

If you need any other informations to try to solve the problem tell me

Thanks for your time

**Comment by she-weeds** [comment]
I think I've had the same problem with one of my Android devices (OnePlus 5 running custom Android 7 ROM) and not the other (Galaxy Tab A 10.1 running... not sure what but probably Android 9). 

The data's clearly been collected because I could see it on QField but when I tried copying and pasting the data files directly from the device's project folder onto a thumb drive (via USB OTG) or a PC (via USB cable), the files would be empty.

The way I worked around it was to copy and paste the collected data to a different location on the Android device (i.e. out of the project folder into say Documents or Downloads), and *then* copy that data from the new location onto the thumb drive/PC. 

I have no idea why this happens and it's a bug I've been meaning to report but haven't had the time to produce MREs etc.

**Comment by Remmug** [comment]
@she-weeds Can you still see the data on the tablet after copy paste it to the computer ? Because in our case the datas are no longer visible in our tablet.

Is your OnePlus5 got this problem since you are on Android 7 or can't you really make a link between the Android OS and the bug ?

Anyway I don't know if your solution will fix our problem due to the difference between ours bug. But if nobody can find a real fix for the problem I will recommend to my colleagues this export technique.

Thanks for your answer

**Comment by m-kuhn** [comment]
Do the updated files appear after a restart of the device?

**Comment by Remmug** [comment]
Ok I read the #400 topic and the topic on the android site (https://android.stackexchange.com/questions/165818/some-folders-and-files-not-showing-up-on-pc-when-connected-via-usb). I didn't know that this was a known recurring problem that could come from Android and not from QField. Although my problem seems to be slightly different I'll check with my colleagues in case the problem comes up again.

I will also look into the clouds however it may be complicated due to the rights of my windows account on thin client computers which requires a long process with management, etc, etc, etc. But I'll spread the word. I'll probably stop adding to this topic, and I or one of my colleagues may come back to answer or ask for the topic to be reopened in several months when the problem has reappeared and the solutions mentioned above have been tested.

To Resume the android topic :
- Some folders and files not showing up on PC when connected via USB
- This is a known issue. Go to app manager and find 'external storage' and 'media storage' and clear data and cache for them, then reboot, and wait up to 10 minutes and then connect to PC via USB. Sometimes media scan apps from play store help if you don't want to reboot.
- app manager : Select show system apps when you go to settings>apps
