### ISSUE TITLE
Bug or Enhancement : Update value relation while editing fields

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#2522]
Hello, 

I don't know if it's a bug or a feature, when a second list depends on a choice from a first list, on the same layer, QFIELD doesn't load the second list. The second list stays blank. 

### Reproduction Steps:

1. Selection of a result in the first list
2. The second list is loaded, depending on the first list => stay blank

### Expected behavior:

On QGIS, the second list is loaded, then I expected the same behavior on QFIELD. 
On QFIELD, I noticed that if you leave the layer's window and reopen it, then the second list is well charged (second video)

### Screenshots and GIFs

Please find below, a video of what it's happening and a picture of what is supposed to happen (from QGIS)

I also attached 2 simplified projects, one of QGIS the other on QFIELD, if you want to test it. 

**QField version:** 
QField version: [1.10.0 (1da006 v1.10/0)]
&
QGIS master-dev (b70957)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

QFIELD Project
[Test_lists_QFIELD.zip](https://github.com/opengisch/QField/files/8078178/Test_lists_QFIELD.zip)

QGIS Project
[Test_lists_QGIS.zip](https://github.com/opengisch/QField/files/8078177/Test_lists_QGIS.zip)

Supposed behavior :
![QGIS - working](https://user-images.githubusercontent.com/72577399/154228186-cfa822f2-c04c-466d-b69b-296c564c7634.png)

Video of the issue :
https://user-images.githubusercontent.com/72577399/154234220-5c4aae71-8534-49f3-b4de-e9419fa45555.mp4

Solution : 
https://user-images.githubusercontent.com/72577399/154233784-80ae41cd-6192-4654-8e10-f72bea17f13a.mp4

Thank you for your attention.

**Comment by she-weeds** [comment]
I think, much like [#2493], the issue might be in your filter expression which to me looks a bit confusing and perhaps unnecessarily convoluted. This is what I got from the OPTIONS layer in your uploaded project:

~~~
Left(attribute(get_feature_by_id('OPTIONS',0),'Compart'),2) >= 3 AND Left(attribute(get_feature_by_id('OPTIONS',0),'Compart'),2) <= 10 

AND

id = array_first(array_agg("id", group_by:= "Code_esp")) AND "Code_esp" is not NULL AND "COMPART" = attribute(get_feature_by_id('OPTIONS',0),'Compart') 
~~~

In the first place if you are trying to filter the SAISIE_PT list using a value from your current feature in the OPTIONS layer, you wouldn't use `get_feature_by_id()` because it will only ever return one feature every time - in this instance, the first digitised feature in the list (index 0). If you don't have any features in your OPTIONS layer then it won't return anything and therefore won't be able to filter the list. 

And even once you have features it will not dynamically filter the list based on your input for each feature, it will always filter by the relevant value in the very first feature in the OPTIONS layer.

Consider troubleshooting with a simpler filter expression, and troubleshoot in QGIS first (I recommend a more stable version such as 3.22 not the latest master build), so that you can be certain that it is QField and not your expression causing the issue.

Here is an example where you want to filter the SAISIE_PT list to make sure that (a) `Code_esp` is not NULL, and (b) the `COMPART` value matches up with the current `Compart` value in your OPTIONS layer.

` "Code_esp" is not NULL and "compart" = current_value('Compart')`

QGIS 3.22:

![filter_list](https://user-images.githubusercontent.com/41975056/154583954-45d6d123-b3c4-4970-a13e-5207b472c044.gif)


Qfield 1.10.0:
https://user-images.githubusercontent.com/41975056/154583761-9520312c-3242-4901-ab40-0364781e2157.mp4

As you can see the list filters correctly. So I would suggest that the filter mechanism is working fine but you need to examine your expression.

**Comment by Ipickedausername** [comment]
Hello, 

I made a few tests. The problem seems to come from a part of my filter expression. 
Mine was more confusing, so I used your, but I added a part to only keep one unique value in the list (elsewhere I could have 300 times the same information). 

Using the expression you proposed : 
`"Code_esp" is not NULL AND "compart" = current_value('Compart') AND id = array_first(array_agg("id", group_by:= "Code_esp"))`

Everything is working, except when I add `AND id = array_first(array_agg("id", group_by:= "Code_esp"))`. 

I already filtered lists in QFIELD using this king of expressions, that means it doesn't come QFIELD but from my filter.

Thank you very much for your answer, this is not a bug. 


I keep it open for a few days, so you can see my answer, and eventually give me some tips if you know how to make the filter works properly. After that I'll close the discussion. 

Thank you !
