### ISSUE TITLE
Value relational form problem

### ISSUE THREAD

**Issue by smoliv** [opengisch/QField#2634]
Hello,
i created a form in QGIS 3.16 with "Relational value" widget for a cascading filter. It works very well in QGIS.
However, in QFIELD when I select a value in my list (relational value field), only the first value is selected. It seems impossible to select other value in my list.

### Reproduction Steps:

1. I Create my QGIS project with cascade filter with a relational value on a first selection list
2. I transfer my project on QField
3. I select a value on Qfield and synchronize with QField

### Expected behavior:

To select the value what I want in my relational value list

### Observed behavior:

Only the first value of my relational value list is selected

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/88040707/159499201-cca49d11-aaf9-488f-8323-be8430a92dd1.png)

**QField version: 1.10.0 

I use only geopackage layers

**Comment by suricactus** [comment]
Hey, @smoliv, can you provide a test project?

**Comment by smoliv** [comment]
Yes, I hope it's ok with this gpkg project

[entretien_vegetation_test.zip](https://github.com/opengisch/QField/files/8325162/entretien_vegetation_test.zip)

**Comment by suricactus** [comment]
There is definitely something wrong, I will look at it in the following weeks.

The entries in the list should not be green.

Note to myself: the .gpkg needs to be renamed without the _test suffix.

![image](https://user-images.githubusercontent.com/2820439/159512349-dbffa2d1-44ad-4395-9ec7-1fcbd4fd15f5.png)

**Comment by smoliv** [comment]
Thanks to help me.
I'm not sure to have saw this problem about the "green list".

We stay informed.

**Comment by nirvn** [comment]
@smoliv , the problem isn't with QField, in fact it's behaving as intended :wink: 

Your value relation widget configuration is incorrect:
![image](https://user-images.githubusercontent.com/1728657/159656025-fa978d86-58f4-4b98-aa18-458bf6bd08aa.png)

The key column should refer to a column with *unique values*, i.e. IDs. The way you have it setup at the moment refers to the "id_type" column, which are shared string values across multiple unique items used to filter your list.

In QField, when you check one item, your configuration registers the id_type value as the selected value, which triggers _all items_ being checked since they all share the same key/ID value.

To fix this, change the key column to "fid".
