### ISSUE TITLE
Orthometric Z registration

### ISSUE THREAD

**Issue by montarob** [opengisch/QField#2670]
I'm using Qfield 1.10.00
I am using Qfield paired with my GNSS Trimble Receiver to collect levels in the field where I'm working on.
I have created a point layer with a Field called "Elevation" where I want to register the z coordinate of the collected points.
I set that field as a "Default Value" in its own widget by settings this variable: z(@positon_coordinate).
In this way, during my survey, it registers on its own the z coordinate.
However the z value registered is the ellipsoidal one and not the orthometric one.
I wonder if there is a way to register the orthometric elevation as well.
Thanks in advance.

**Comment by gdt** [comment]
I wonder why you are using an elevation field rather than a 3D CRS.   If you used a 3D CRS you could use the normal transforms.

You are talking about HAE and orthometric height, but you don't mention either datum.  Were I trying to what you are doing, I'd be using NAD83(2011) epoch 2010.0 elllipsoidal coordinates and then transforming to NAVD88 heights.  But you might be using ITRF/WGS84 ellipsoidal coordinates and want "WGS84 Orthometric Height" via EGM2008.   Or your national 3D datum and a national/regional  height datum (e.g. ETRS/EVRF).

**Comment by gdt** [comment]
@montarob What form is the data from the Trimble?  Is it NMEA?  If so, is it putting some kind of orthometric height in the elevation field, and the geoid offset used in that field, or is it reporting HAE in the elevation field?    HAE in the elevation field is non-compliant but useful, and QField would need a setting (which it might have) to specify that NMEA elevation is really HAE instead of the NMEA definition.
