### ISSUE TITLE
Paths in aboutdialog

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#272]
Excluded from #130 

Path (of shared elemnts) is shown in “settings/about” only directly after first start and path gets lost after following starts of qfield.
![39123130-27e0e288-46f7-11e8-9c83-1418da53724f](https://user-images.githubusercontent.com/28384354/39189073-abb398aa-47d1-11e8-8369-3575412f298c.png)

**Comment by geostonemarten** [comment]
need to be reopeen same problem on 1.0.0 rc3 on french version. I don't no if it is affected by translation

version is truncated;

I have this in my about box:

_Version de Qfield : 1.0.0-rc3 - M...
Dossier des paramètres de QField :
Dossier des éléments partagés de QField_

I send a request for transiflex translation because I see some spelling error. It is possible to update documentation in addition because it's 0.10 in website or we are on 1.0 on play store ?

**Comment by suricactus** [comment]
@signedav is this still revelevant?

**Comment by signedav** [comment]
No
