### ISSUE TITLE
Import project from zip

### ISSUE THREAD

**Issue by robibrazze** [opengisch/QField#2783]
Hi,
i tried to import project in Qfield mobile from file zip but dont work, after selecting the file it does not load it.
I used Android 11 and last version og Qfield.
Any help is welcome.

thanks
Roberto

**Comment by nirvn** [comment]
@robibrazze , if you can share a screencast and possibly the zip, that'd be helpful in dissecting

**Comment by robibrazze** [comment]
@nirvn , below report log error
![image](https://user-images.githubusercontent.com/28442671/164259382-ddc4f81a-9d3d-4061-9fbe-66283347ecca.png)

**Comment by nirvn** [comment]
@robibrazze , is there anything in your imported projects folder?

**Comment by nirvn** [comment]
@robibrazze , ok, there's an issue with folders in the ZIP archive. If you compress your project file and datasets so that they are in the root of your ZIP, it'll work fine (ie when you open your ZIP file on your desktop, you should see your files directly, not a folder that contains your files).

It'll be fixed ASAP.

**Comment by nirvn** [comment]
@robibrazze , the APKs in this PR should fix your issue (https://github.com/opengisch/QField/pull/2786)

**Comment by robibrazze** [comment]
@nirvn , thanks, the problem is the folder that contains my files, into the folder ZIP. To work well the zipper folder must contain only the files and not another folder

**Comment by nirvn** [comment]
@robibrazze , fixed in 2.0.16.
