### ISSUE TITLE
Error in XYZ Tiles layer projection

### ISSUE THREAD

**Issue by cgaldini-datek22** [opengisch/QField#2793]
XYZ Tiles Layer in Qfield are projected in wrong way.

I created a simple QGIS project, Maps EPSG:32632
I added a XYZ Tile layer configured as Google Satellite
I imported project in QField 2.0.15 (arm64-android)

I Expected to view the layer in the right coords.

The location of XYZ Layer is not correct. The Y coords are wrong.

QField Version: 2.0.15 (0c5bde)

i send the simpe project and video

https://user-images.githubusercontent.com/49910072/164441365-361ff2d9-c721-4aea-89d3-42629a8515ef.mp4

thanks
Cristian

[test.zip](https://github.com/opengisch/QField/files/8530199/test.zip)

**Comment by nirvn** [comment]
@cgaldini-datek22 , I see this project file was saved using QGIS _3.10_ :fearful: when opened against the latest QGIS 3.22 LTR, I see the project's CRS is set to no projection, which would give you bad coordinate.

I'm afraid the problem here is your project setup, not QField. 

Suggestion:
1/ Help yourself, use the latest QGIS LTR (3.22.6) or the latest stable release (3.24.2)
2/ Make sure your project CRS is set to match the coordinates you want

**Comment by cgaldini-datek22** [comment]
hi,
thanks, actuallt i posted a different versione of project files (without CRS), sorry.
this attached one is intended to reproduce the issue.
[test.zip](https://github.com/opengisch/QField/files/8530412/test.zip)

thanks
Cristian
