### ISSUE TITLE
Issue with qfiedSync and qgis2compat in qgis 3.0.0

### ISSUE THREAD

**Issue by zakigates** [opengisch/QField#283]
I'm encountring an issue with installing qgis2compat and qfieldsync in QGIS 3.0.0
### Reproduction Steps:

1. Download the latest versions of plugins
2. Go to the plugin manager
3. Install from zip

### Expected behavior:
After these 3 steps the extensions must be succesfuly installed though I'm having the folowing errors: 

**qgis2compat :** warning : `Due to the very special functionality provided by qgis2compat it cannot be loaded/unloaded ([un]checked in the plugin manager). If you don't need it anymore, please uninstall it.
`
**qfieldsync :**  `No module named 'processing.core.AlgorithmProvider'`

Please if you could help me fix this issue I would be pleased.
Regards.

**Comment by m-kuhn** [comment]
QFieldSync for QGIS 3 does not need qgis2compat and has not yet been released.

There is however a testing version which needs a slightly more complex installation setup (needs manual copying instead of install from zip). See here: https://github.com/opengisch/qfieldsync/issues/66#issuecomment-374975095

**Comment by zakigates** [comment]
Hello,
I did as described but when I past the folder into the plugin repository I'm told that the metadata file is missing. When I look for it in the qfieldsync folder I dowloaded from the link you gave, I don't find it.
Any solution for this?
