### ISSUE TITLE
Keep the session active in QField

### ISSUE THREAD

**Issue by Fertuesta25** [opengisch/QField#2869]
### Describe the issue
It would be interesting to save the login in QField, it is inconvenient to have to login every time you want to send changes or synchronize.

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.2]
 - QFieldSync Version [e.g.4.1.0]

### Mobile (please complete the following information)
 - Device: [e.g. moto g(50) 5G]
 - OS: [e.g. Android 11]
 - QField version: [2.1.2 1c22b0]

**Comment by suricactus** [comment]
Did you login on another device? If yes, it is expected behaviour. 

Can you confirm you can reproduce the following steps:
1) Open QField
2) Login to QFieldCloud
3) Close QField and remove it from running apps on your device
4) Open QField
5) Open QFieldCloud screen - you should login automatically

**Comment by Fertuesta25** [comment]
Thanks @suricactus , it works correctly.
