### ISSUE TITLE
Vertex tool: allow to select vertices on press instead of opening the form

### ISSUE THREAD

**Issue by olivierdalang** [opengisch/QField#2917]
### Describe the issue

Currently, when in vertex editing mode, when you click on a vertex, the feature is selected and the attribute form opened. This is not very useful (the form was opened right before one decided to edit the geometry) and even annoying on mobile (where the form takes too much space to allow properly editing the geometry).

Instead, why not select the vertex that is being edited ? That would be a nice alternative to the prev/next vertex buttons when vertices are sufficiently spaced for direct selection.

### Reproduction steps

1. Enable edit mode
2. Select a feature
3. Press on vertex tool button
4. Press on a node

### Expected behavior
The node gets selected

### Observed behavior
The feature gets selected and the form opens

### Screenshots and GIFs
-
### Desktop (please complete the following information)
- N/A

### Mobile (please complete the following information)
 - Device: Motorola G6 play
 - OS: Android
 - QField version: 2.1.4.496792

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: ?
* Problem can be reliably reproduced, doesn't happen randomly: yes
* Problem happens with all files and projects, not only some files or projects: yes

**Comment by Ipickedausername** [comment]
Hi ! 

Maybe this is a bug. 
Instead of opening the attribute form (which is not useful as you said) QFIELD could : 
- Allow editing the geometry of the selected form
- Do nothing (to avoid mistakes when too many vertexes are crossing)

In the same way, there is no real use to open the list of actions (bookmarks, coordinates, etc.) when pushing on the screen for too long, when we are on editing mode. 

Here I add 2 video to illustrate the situation. 

https://user-images.githubusercontent.com/72577399/169914443-a6b86db4-405e-40b8-9c1b-f05f7e12676b.mp4

https://user-images.githubusercontent.com/72577399/169914985-76a91644-c9d9-4792-88ef-2b1b7b55c483.mp4

Hope I well understood the situation.

**Comment by nirvn** [comment]
@olivierdalang , hey, hope you are doing well wherever you are :) -- this has been implemented already. Closing.
