### ISSUE TITLE
Can't open project

### ISSUE THREAD

**Issue by grdaveygrd** [opengisch/QField#332]
I've been using QField very successfully on a tablet with Android 5.1.1 and QField 0.10.13. Now I have a new tablet with Android 7.0 and QField 0.11.0. I have copied my QGIS project to the same location, but can't find this location when trying to open the project from QField. Specifically the Android directory does not show up. I have seen this question asked, but not answered, elsewhere.

**Comment by m-kuhn** [comment]
What happens if you put the files into another directory?

**Comment by m-kuhn** [comment]
Are they located on an external SD card or internal memory?

**Comment by m-kuhn** [comment]
Internal memory is normally easier. Funny story: the internal memory can be found under `/sdcard` inside the file browser.

Btw, it's also possible to use another standalone file explorer and open the `.qgs` project from there.

**Comment by grdaveygrd** [comment]
I'm finding the Android file system mystifying. I had tried to open a project with the built-in file explorer, didn't work. I installed Total Commander, that lets me see the files where they are and I can open projects from this. But my geopackage images don't open, Tif files do. My svg characters aren't opening and I'm getting the error message Can't open database... multiple times when I scroll or zoom.

**Comment by m-kuhn** [comment]
> I'm finding the Android file system mystifying

Us too, we are working on it ;)

> I installed Total Commander, that lets me see the files where they are and I can open projects from this. 

Great, so the root issue is solved.

> But my geopackage images don't open, Tif files do. My svg characters aren't opening and I'm getting the error message Can't open database... multiple times when I scroll or zoom.

I guess that's all related, probably the gpkg also opens but is in a different CRS than the project itself and because the CRS database cannot be opened it is not able to reproject properly.

I will close this in favor of the already existing issues
https://github.com/opengisch/QField/issues/299 https://github.com/opengisch/QField/issues/286 please add any additional information you have there
