### ISSUE TITLE
Duplicate also child features when parent feature is duplicated

### ISSUE THREAD

**Issue by sbuettler** [opengisch/QField#3449]
Enhancement proposal: in relational tables child features aren't duplicated when parent features are duplicated. Qfield doesn't offer this functionality by now.

**Comment by Ipickedausername** [comment]
Hi, 

I was plannint to post a similar idea, just want to add that, for duplicate a relation, we need Qfield to update the field used for the relation. Because usually having 2 parents and 2 childs "inter-related" is not very useful. 

It can also bring to errors, if we update the child after duplicating it, because it will have unoque informations, but with 2 parents (which one is what...)

It would be better to have several options when clicking on duplicate (when the layer has relations), like: 
- duplicate with same id
(Same parent and child, /!\ the child must not be updated to avoid errors)

- duplicate and update fields
(All the fields with default value or relation, like id, coordinates, etc. are updated

**Comment by m-kuhn** [comment]
I think we should follow the rules that QGIS has on this (if that's not the case already)
https://gis.stackexchange.com/a/443158/9839

**Comment by Ipickedausername** [comment]
I'm using "composition" between relations layers. 
When I use duplicate in the parent layer, there is no duplication for the child layer. 

Is it the way it works on QGIS ? I noticed that I don't know how to duplicate on QGIS..

**Comment by m-kuhn** [comment]
See https://github.com/qgis/QGIS/pull/5448 and https://github.com/qgis/QGIS/pull/36285

**Comment by nirvn** [comment]
@sbuettler , implemented, children will be duplicated for relationships set to composition mode.
