### ISSUE TITLE
Can't open files from Qgis in QField

### ISSUE THREAD

**Issue by saar324** [opengisch/QField#3668]
### Describe the issue
After transferring a project from Error to QField several error messages appear and the project cannot be viewed on the phone.

### Expected behavior
The files will open in the QField app

### Observed behavior
Error massages and I can't open the layers

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/118734522/203045303-80ebeeff-2b1d-4b88-b0fa-d7f1882263f9.png)

![PastedGraphic-1](https://user-images.githubusercontent.com/118734522/203045466-8565b77a-a605-409e-a51d-fc1f73527827.png)
![PastedGraphic-2](https://user-images.githubusercontent.com/118734522/203045481-5aeedc33-99db-4982-b8ec-19cbfc5fb59a.png)
![PastedGraphic-3](https://user-images.githubusercontent.com/118734522/203045510-606c09d5-8c0a-45b0-9191-97e9ef98b312.png)

### Desktop (please complete the following information)
 - OS: [macOS ventura 13.0.1 ]
 - QGIS Version [3.28.1]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@saar324 , at look at the screenshots you attached reveals that your project isn't "portable" (relies on absolute paths instead of relative, and likely refers to datasets outside of the folder and subfolders within which your project file is located) and therefore won't work on QField. Please read this short introduction to portable projects in the documentation: https://docs.qfield.org/how-to/movable-project/

**Comment by saar324** [comment]
Very helpful thanks!!




Best regards,

Saar Reshef
VP Business Development and Innovation,
Reshef aviation
