### ISSUE TITLE
Make screen Track gps

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField#37]

**Comment by m-kuhn** [comment]
Caveat: redrawing the map canvas is expensive (until we switch to a tile based, cached renderer) so redraw on every update may not offer the best UX.

We'll probably only want to update after a move of more than a few `dp` or a certain portion of the screen.

Idea:

* In navigation mode: when GPS position is inside a margin of 2/3 of the screen diameter, recenter whenever it leaves this area.
* In digitizing mode
  * by default behave the same
  * Point locator snaps to the current location (4dp tolerance, to be tested) when snapped, the locator follows the current location and the screen recenters when the location is further away from screen center than the tolerance. Snap lock can be released with a button (or a screen move?)

**Comment by mbernasocchi** [comment]
ok understood.
the rest makes sense.

**Comment by EulenspiegelTill** [comment]
* _In navigation mode: when GPS position is inside a margin of 2/3 of the screen diameter, recenter whenever it leaves this area._

This feauture would be a great support in digitizing mode when cursor is attached to the location. 
If you're struggling through the bush with an external GNSS receiver, it's helpful to save on screen clicks. It should be possible to switch the function on and off, because the accuracy of the GPS varies depending on the field measurement. At an accuracy of +/-10m which would be partly disturbing, but very helpful if you walk a whole day through the field with an accuracy of +/- 2cm.

**Comment by m-kuhn** [comment]
@nirvn can this be closed?

**Comment by nirvn** [comment]
Ya

**Comment by m-kuhn** [comment]
:tada:
