### ISSUE TITLE
Problem with background in Qfield

### ISSUE THREAD

**Issue by GianlucaAgr** [opengisch/QField#3748]
Good morning 
in Qfield (Android) with some project whith google or other background configured in QGIS 3.22 LTR (Mac) i see the following message in Qfield: caught a coordinate system exception while trying to transform a point. Unable to calculate line lenght, and the background don't work.

**Comment by nirvn** [comment]
@GianlucaAgr , we'll need more information. 

QField version, OS on which QField is run, test project files, screencast if possible.

**Comment by GianlucaAgr** [comment]
Qfield v.2.4.6 on Redmi Note 10 Pro Android 12  
[Castellazzo Bormida .zip](https://github.com/opengisch/QField/files/10254317/Castellazzo.Bormida.zip)

**Comment by nirvn** [comment]
@GianlucaAgr , I've not been able to replicate this issue using the .zip file you provided. It could be because the WMS layer was not online / accessible to me.

Could you:
a/ give QField's latest public version (v2.6.1) a try and see if the situation has improved;
b/ if you are still seeing this issue, could you provide another test project and make sure all layers are available? You mentioned that you were seeing this with a 'google' basemap. Assuming it's an XYZ basemap, try that, it'll increase the chance I can test it out.
