### ISSUE TITLE
Features lost on QField app while trying to sync

### ISSUE THREAD

**Issue by cez2020** [opengisch/QField#3860]
Points disappearing on QField app after syncing.

1. I added some point features (with attributes) to my project (on the app).
2. I pushed my changes to the cloud and then proceeded to add more points and then pushed again.
3. However, after I sync (using the synchronize button), I am unable to see (on the app) the features that I had just added to my project.
4. Although I am able to see them in my Qfield cloud project (in QGIS), my newly added features just won't appear in the project on the app (mobile device).
5. I tried reloading the project several times but keep getting the same outcome

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version: 3.16 LTR Hannover
 - QFieldSync Version: 4.2.0

### Mobile (please complete the following information)
 - Device: iPhone13
 - OS: iOS 16.2
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)] Unable to find :/

### Additional information
* Problem has occurred several times since installation. Although it appears no data has been lost, there seems to be a synchronization issue.
* Login: rightonq

**Comment by suricactus** [comment]
Could you please provide additional information about your username and project name?

**Comment by cez2020** [comment]
@suricactus I've updated my post with additional information

**Comment by DColby-UMS** [comment]
Having the same issue..  https://github.com/opengisch/QField/issues/3893

**Comment by suricactus** [comment]
@cez2020 You never mentioned which project you experience the problems with.

A few questions to provide us with some information, which will help solving your issue.

1) You do not have layers with Z or M values, right?
2) Have you tried wtih QField 2.5.x version? 
3) I assume sometimes it works fine, sometimes it doesn't?
4) What happens if you:
a) push your changes and sync them back right away? 
b) push your changes and sync them after a few minutes? 
c) push your changes, delete the project on the phone and download it again.
