### ISSUE TITLE
Vertical Accuracy Reporting

### ISSUE THREAD

**Issue by DrawQuick** [opengisch/QField#3905]
### Discussed in https://github.com/opengisch/QField/discussions/3890

<div type='discussions-op-text'>

<sup>Originally posted by **DrawQuick** February  7, 2023</sup>
Hello Qgis Developers
I'm using a U-Blox c099-f9p evaluation board and connecting to an Ntrip on RTK2GO using Android App Bluetooth GNSS version 1.0.39.
This app reports the horizontal and vertical accuracy from the board correctly. Qfield shows the same horizontal accuracy but not the vertical accuracy. Typically a difference of +1.2metres. As an example, if the board is reporting 0.04m Qfield is reporting 1.24m.
Also under Settings, Positioning tab, 
"Bad accuracy below[m]" should read
"Bad accuracy above [m]"
and
"Excellent accuracy above[m]" should read
"Excellent accuracy below[m]"
Example: If the accuracy is above 1m that is bad accuracy and an accuracy below 0.05m is excellent.
Thank you</div>

**Comment by ConJaySten** [comment]
Did you ever resolve the vertical accuracy issue?  The same thing is happening to me with GNSS Master and Qfield.  GNSS Master shows 10-15mm vertical accuracy after NTRIP correction, but Qfield shows over a meter.  I'm assuming it's some kind of problem with NMEA codes.

**Comment by nirvn** [comment]
@DrawQuick , any updates on this? Has the issue been resolved?

**Comment by DrawQuick** [comment]
Hi Mathieu,
I haven't had a chance to verify. I live in Canada and was sleeping while
you were fixing. I'll have a look at it today. Thanks for your
quick response!

**Comment by gdt** [comment]
I am using QField with a sparkfun RTK Express.  I see reasonable errors, going to 0.014m when in FIX.   Yes, this is horizontal.  I suggest that the original reporter make a more detailed careful report with actual accuracy values, along with the results of an experiment to see if they are correct.   For example, I have returned to a specific  "iron rod"  multiple times days and months apart, taking 30s average each time, and my points cluster within about 4cm, with 0.014m accuracy reported.  To me this is a good outcome; the accuracy reports are always optimistic.

**Comment by vinhloifr** [comment]
> Did you ever resolve the vertical accuracy issue? The same thing is happening to me with GNSS Master and Qfield. GNSS Master shows 10-15mm vertical accuracy after NTRIP correction, but Qfield shows over a meter. I'm assuming it's some kind of problem with NMEA codes.

Hi, I have the same issue, my Leica GPS GG04 supports the altitude correction very well with RTK. GPS can connect with Qfield via bluetooth, and I think there is no problem about coordinates but the altitude correction. I compare many elevations collected from Qfield, there is a difference of 1m2 with my reference data.

I try to download some vertical grid files and put them correctly on the path for test, but there is no better data return.

I hope someone can share me about this subject. I appreciate for that. Thank so much.
Best regards,

**Comment by gdt** [comment]
@vinhloifr I think you are having a problem which is off topic for this issue.   I'll give some hints and suggest that you open a new issue.

You say there is an error, and that indicates that you have some mark surveyed well enough that you believe the coordinates.   I am guessing (this is a huge clue: you should write bug reports and requests for help so that people do not need to guess!!) that you have measured that same point with RTK.   So, the question is 1) what did you really do?  say it, don't make us guess.   2) what was the *reported* H and V accuracy in QField while doing this.

My hints are:

1) Also install https://github.com/semuconsulting/pyubx2 and see what you get.

2) Make sure you understand what datum your surveyed mark coordinates are in, and what datum your RTK positions are in. 

2A) Make sure you understand the antenna height input field, and that you need to transform from APC to bottom of rod, or something else that you understand.

2B) Understand that QFIeld, because it uses proj, will do null transforms for situations where that is not geodetically sensible.

2C) Understand that QFIeld does not have a way to label the incoming data as other than WGS84, and worse, that WGS84 is an ensemble with a low-accuracy member.

3) GPS receivers have terrible geoid models and the only sane path is to disable the receiver's orthometric computations, and log HAE from the receiver.  perhaps then to apply a HAE-to-orthoometric geoid model.

My guess is that there is a significant probability that you are blurring "WGS84" and a national plate-fixed datum and running afoul of some of my guidance above.   Followups about this in a new ticket is my opinion.   (I have no authority.)
