### ISSUE TITLE
After synchronizing data on Qfield, it was successful but after that the features disappeared and cant see the point features or any picked features

### ISSUE THREAD

**Issue by abz-cyber** [opengisch/QField#3911]
We are currently working on a project in Kenya and were using Qfield to collect data. The people on ground picked some point data and synchronized it but the point data disappered i cant see it on the project layer
### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - OS: [e.g. Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by suricactus** [comment]
Can you please share what are your QFieldCloud username and project name. Please use the template in your original message and replace the information in the square brackets.

**Comment by goldenricky** [comment]
I have the same issue, after press sync in qfield from my android cell phone, it show success but the updated data disappeared in the qfield and no update in desktop qgis.

My andriod ver: emui 12.0.0 (huawei mate 20)
Qfield android ver: 2.6.3 - geeko gecko
Qgis desktop ver: 3.22.6
Qfield sync plugin ver: 4.4.8

Dure to the sync error in qfield andriod, i use push change mode for updating in qfield cloud, but qfield cloud show error as attr
ached photo. 
![16783762092902687097816123536713](https://user-images.githubusercontent.com/123293180/224074495-04b0154e-03e1-4187-83d9-3235cdf9e867.jpg)

I guess the issue have been occured 2 to 3 weeks ago. 

Is the error come from out of data storage in qfieldcloud or not? @@
![16783764438783879361461070777852](https://user-images.githubusercontent.com/123293180/224075604-108b91fe-dd4a-45ca-88ab-c93db0c29fb5.jpg)


Thx

**Comment by goldenricky** [comment]
My username :  rickyho
project name : Treemap_v12

**Comment by stempest123** [comment]
Please could anyone let me know if this issue has been resolved as I am experiencing the same issue today 
![image](https://user-images.githubusercontent.com/128692753/227167548-c571f234-143d-4395-890b-61561591a08c.png)

**Comment by ZsanettMed** [comment]
Hello!
@goldenricky, yes, your issue is most probably related to the limited storage capacity as a Community user. You can either upgrade your account or delete (older) project files (and versions). 
If you have missed the BETA-transition announcement you can read more about it here: https://qfield.cloud/beta-transition.html or in our [FAQs](https://qfield.cloud/faq.html)
More information about pricing here: https://qfield.cloud/pricing.html

@stempest123, do you have the same warning ("You are running out of space...")? If yes, please read my response above. If not, please drop us an email (beta-transition@qfield.cloud) with more details. 

@abz-cyber do you still have this issue? If yes could you please provide us more information about it (via mail to: beta-transition@qfield.cloud)? 

Thank you & best regards, 
Zsanett
