### ISSUE TITLE
QField synchronisation failed

### ISSUE THREAD

**Issue by cocro** [opengisch/QField#447]
Hello,
I come back to you for a synchronization concern for the least surprising

Screen copies explain my concern. The Qgis project was generated version 3.4, the synchronization done once, copied on the two tablets of my investigators. Inverse synchronizations are done by copy-pasting on the PC and launching the Qfield 1.0 extension

PC_avant_synchroPaul & PC_avant_synchroMelanie = context read under Qgis 3.4 before synchro
![pc_avant_synchromelanie](https://user-images.githubusercontent.com/46560615/51523804-bbd1e480-1e2c-11e9-923b-69d68b768a27.PNG)
![pc_avant_synchropaul](https://user-images.githubusercontent.com/46560615/51523808-beccd500-1e2c-11e9-9dfc-4dc5400ae927.PNG)

Tablet_dossier_PAUL2201 & Tablet_dossier_MELANIE2201 = contents of the folder on the Tablet
I noticed that the data.gpkg-shm and ata.gpkg-wal files are not always present on the tablet. What are they? The recording time is different from data.gpkg, why?
  
![tablet_dossier_melanie2201](https://user-images.githubusercontent.com/46560615/51523817-c3918900-1e2c-11e9-97a6-7123e212af48.PNG)
![tablet_dossier_paul2201](https://user-images.githubusercontent.com/46560615/51523822-c5f3e300-1e2c-11e9-8f81-3ae293fb7eab.PNG)

PC_apres_synchroPaul & PC_apres_synchroMelanie = context after synchronization
points turn yellow while the investigator did not intervene on the tablet
points remain to be grasped (diamond points) while they have been updated
![pc_apres_synchromelanie](https://user-images.githubusercontent.com/46560615/51523832-cdb38780-1e2c-11e9-920c-43fe30549d30.PNG)
![pc_apres_synchropaul](https://user-images.githubusercontent.com/46560615/51523837-d015e180-1e2c-11e9-860d-4d00a033ac62.PNG)

PC_data_spatialLite_MelaniePAul_OK: The data tables read in a SpatialLite database do not reproduce the visual errors of the synchronization
![pc_data_spatiallite_melaniepaul_ok](https://user-images.githubusercontent.com/46560615/51523908-fdfb2600-1e2c-11e9-9c71-4bbd738f82cc.PNG)

Thank you for enlightening me on this dysfunction.
Certainly not blocking because I can work via SpatailLite but does not reassure the researcher unfamiliar with the geographical tools

**Comment by saemiw** [comment]
I cannot quite follow @cocro's example but I am also unable to use the QFieldSync-Plugin with QGIS 3.4.4 and 3.5 nightly built QFieldsync-Plugin version 3.0.3. Data entered in offline-mode are not synchronised, but QFieldSync does not return an warning or error at all.

Maybe linked to one of these issues?
- https://github.com/opengisch/QField/issues/441
- https://github.com/opengisch/qfieldsync/issues/94

It used to work as I commented [here](https://github.com/opengisch/qfieldsync/issues/94)

**Comment by signedav** [comment]
It seems that without closing the project on QField we loose the last data on synchronization:

**Test with closing:**
1. copied the project to my mobile
2. edits, and opening other project or closing qfield
3. copied the project to computer and sync (without closing on mobile)
-> changes are correctly synchronized

Though `wal` files are sometimes still existent (possibly new once)

**Test without closing:**
1. copied the project to my mobile
2. edits
3. copied the project to computer and sync (without closing on mobile)
-> changes are not synchronized


Some more checking the files during editing:
1. copied the project to my mobile
2. I edit and `-wal` file appears, I edit and edit. I check sometimes over the computer the files in the folder. Suddenly no `-wal` file is there anymore
3. I continue editing, the `-wal` file appears again but does not disappear.
4. I copy the folder to my computer and make the synchronization with QFieldSync -> Only the edits until 2 (until the disappearing of the -wal file) are synchronized.

What is wal file? https://www.sqlite.org/wal.html
> The traditional rollback journal works by writing a copy of the original unchanged database content into a separate rollback journal file and then writing changes directly into the database file. In the event of a crash or ROLLBACK, the original content contained in the rollback journal is played back into the database file to revert the database file to its original state. The COMMIT occurs when the rollback journal is deleted.

> The WAL approach inverts this. The original content is preserved in the database file and the changes are appended into a separate WAL file. A COMMIT occurs when a special record indicating a commit is appended to the WAL. Thus a COMMIT can happen without ever writing to the original database, which allows readers to continue operating from the original unaltered database while changes are simultaneously being committed into the WAL. Multiple transactions can be appended to the end of a single WAL file.

Setting the WAL functionality works with `PRAGMA journal_mode=WAL;` implementations regarding that are e.g. https://github.com/qgis/QGIS/commit/f939e9cff598b95e95b0de099d0c9a92eed0ea9c

When we do something on QGIS-Project, then close it, the `wal` file disappears (means it's committed). 
> By default, SQLite will automatically checkpoint whenever a COMMIT occurs that causes the WAL file to be 1000 pages or more in size, or when the last database connection on a database file closes.
(https://www.sqlite.org/wal.html)

For closing GDAL/OGR is mentioned here https://gis.stackexchange.com/questions/199365/force-python-gdal-ogr-to-flush-changes-to-disk/199455#199455

**But I assume the issue is, that the QField project is not closed before the synchronization (no disconnecting or dataset closing)**

So I see two possibilities:
- Bring the user or the QField itself to close it, before copying the files
- QField needs to make COMMITS (question is when? After every change? On getting to standby?)
- WAL mode needs to be disabled

## Disable WAL mode
This would be possible:
> These are the two ways reported by Even Roualt for turning WAL mode off from QGIS:
People can either define the OGR_SQLITE_JOURNAL environment variable to DELETE or set the QGIS setting "/qgis/walForSqlite3" (in advanced mode) to false, and this will prevent QGIS from enabling WAL on opening. The drawback is potential deadlocks in some situations where a reader and writer would run concurrently.
(from https://gis.stackexchange.com/questions/224188/geopackage-error-is-mounted-and-in-wal-mode-this-combination-is-not-allowed)

The "/qgis/walForSqlite3" I cannot find in the AdvancedSettings so I set the environment variable.
But it still creates the WAL files... Have to check that...

**Comment by saemiw** [comment]
Maybe also linked to this: https://github.com/opengisch/QField/issues/185

**Comment by signedav** [comment]
@saemiw and @cocro could you please make tests with https://download.opengis.ch/qfield/ci-builds/qfield-dev-454-5bddef261576bc933e4388da1a74f754e3fe9c65-armv7.apk
First if the synchronization works and whether you do not have any other troubles?
Be aware - this is just a test build not to work with productively.

**Comment by saemiw** [comment]
I tested both ways of synchronising: 

**Without QFieldSync**-Plugin (copy'n'paste in order to replace old files): Seems to work. No wal-files appear. Data are synrhonised as expected. I did not test very extensively though. 

**With QFieldSync-Plugin**: To my surprise the geometry of newly added points was synchronised (I expected differently due to [this](https://github.com/opengisch/qfieldsync/issues/96)). BUT the text attributes I recorded were lost (not synchronised).

**Comment by signedav** [comment]
Is it possible to provide me your project @saemiw ?

**Comment by cocro** [comment]
Thank you for your tests, I understand that you do not reproduce my concern.
I cut / paste the contents of the tablet folder on my PC
Synchronization via the QField sync plug-in gives me wrong information. Points change to yellow when the update has not been made (modified captions) and others remain colored without changing tables while the entry has been made.
![qfield_synchro_faux](https://user-images.githubusercontent.com/46560615/51899325-16ca8500-23b3-11e9-8ac4-144b9b3ad3a0.png)

Synchronization via the opening of data.gpkg (spatialite) gives me the correct color code and good attribute data
![qfield_synchro_vrai_spatiallite](https://user-images.githubusercontent.com/46560615/51899348-1df19300-23b3-11e9-85bc-29764c8a95d6.png)

The simplest would be to exchange in french and / or to transmit my dataset in mp for you to do tests.
Les enquêteurs sont partis avec les tablet, je ne peux installer le apk....
Mais avant de le faire, il y a-t-il un risque sur le projet actuel en production ?

**Comment by cocro** [comment]
I did not see your last answer.
Yes, I can send you my project to understand my concern.
Give me the approach to follow

**Comment by signedav** [comment]
@cocro ce sont les tests avec le QField de le Playstore ou le QField de hier?

**Comment by cocro** [comment]
Toujours les résultats avec le Qfield du Playstore

**Comment by saemiw** [comment]
> 
> 
> Is it possible to provide me your project @saemiw ?

Yes sure. It is very basic, only designed to test without any other confusing setups:
[qfieldsync-bug.zip](https://github.com/opengisch/QField/files/2807467/qfieldsync-bug.zip)

**Comment by cocro** [comment]
Voici le projet exporté depuis Qgis 3.4 avec extension QField 3.0.3
copié/collé 
[enquete19_pdr_sans_detail2.zip](https://github.com/opengisch/QField/files/2807741/enquete19_pdr_sans_detail2.zip)
sur samsung Galaxy Tab android 8.1

Voici le projet importé depuis cette tablet où est insallé QField v1.0 (07/01/2019) pour être synchroniser sur le pc
[enquete19_pdr_melanie29.zip](https://github.com/opengisch/QField/files/2807752/enquete19_pdr_melanie29.zip)

Merci pour vos retours

**Comment by 3nids** [comment]
@saemiw do you have any date/time field in your project?

It might be worth merging #421 and rebase this one.

**Comment by 3nids** [comment]
I am just trying to be sure that the issue of date/time field was not interacting here too.
Merge is about integrating the fix of date/time from the other pull request, and rebase means that this current pull request would have integrated this work.

But it should be good as is,  since you were doing the things pretty well by not using any date/time field. Thanks again for your prompt testing and replying, as usual!

**Comment by saemiw** [comment]
https://github.com/qgis/QGIS/commit/22034aa070

Von: Denis Rouzaud [mailto:notifications@github.com]
Gesendet: Dienstag, 29. Januar 2019 14:40
An: opengisch/QField
Cc: Wechsler Samuel; Mention
Betreff: Re: [opengisch/QField] QField synchronisation failed (#447)


I am just trying to be sure that the issue of date/time field was not interacting here too.
Merge is about integrating the fix of date/time from the other pull request, and rebase means that this current pull request would have integrated this work.

But it should be good as is, since you were doing the things pretty well by not using any date/time field. Thanks again for your prompt testing and replying, as usual!

**Comment by 3nids** [comment]
> qgis/QGIS@22034aa

What do you mean? This is already part of QField since it's in QGIS master.

**Comment by saemiw** [comment]
> 
> 
> > [qgis/QGIS@22034aa](https://github.com/qgis/QGIS/commit/22034aa)
> 
> What do you mean? This is already part of QField since it's in QGIS master.

sorry, that was not designed for this thread...

**Comment by saemiw** [comment]
> **With QFieldSync-Plugin**: To my surprise the geometry of newly added points was synchronised (I expected differently due to [this](https://github.com/opengisch/qfieldsync/issues/96)). BUT the text attributes I recorded were lost (not synchronised).

@signedav: After updating to QGIS 3.4.4 (from 3.4.2) the problem with the non-synchronised attributes disappeared!

**Comment by signedav** [comment]
Thanks. Then I think we can go for this solution.

**Comment by saemiw** [comment]
oh man... in order to give more information on this https://github.com/opengisch/qfieldsync/issues/63 I retried to set data offline and synchronise them. And to my surprise I failed. I used QGIS 3.4.4, QFIield 1.0.0-rc3, QFieldSync 3.1.1. I has worked at some time. Does this make sense to you guys?

Below my project. Try to:
1. set it offline with qfieldsync
2. copy the offline files on your tablet and add a point
3. copy the offline files from the tablet on the computer
4. synchronise with qfieldsync
[synchonising wiht qfieldsync.zip](https://github.com/opengisch/QField/files/2906218/synchonising.wiht.qfieldsync.zip)

**Comment by saemiw** [comment]
Update: In the meantime I tested on two different devices. On one the same project (same QGIS, QField, QFieldSync versions) works perfectly (Android Version 5.1.1, model SM-T365) on the other points are not synchrnosed (Android Version 8.1.0, SM-T395). Maybe the android version is an issue?

Additionally I am able to synchronise some older projects (not the one provided here) even with the "problemlos" tablet (Android Version 8.1.0, SM-T395). Has there been changes in how geopackage specification or something the like?

**Comment by saemiw** [comment]
With this project ([syncing works with qfieldsync.zip](https://github.com/opengisch/QField/files/2926799/syncing.works.with.qfieldsync.zip)) I cannot reproduce the issue. I don't see whats de difference to the project supplied here. https://github.com/opengisch/QField/issues/447#issuecomment-467487201. 

So in summary I have two different (very simple) projects and QFieldSync does not behave the same... Can anyone reproduce or even better understand?

**Comment by signedav** [comment]
Thanks for reporting @saemiw I'll check that out.

**Comment by saemiw** [comment]
The lastest update of the qfieldsync-Plugin (https://github.com/opengisch/qfieldsync/releases/tag/v3.1.3)  seems to fix the issue. I can't reproduce it anymore. Thanks for you fantastic effort guys!

**Comment by m-kuhn** [comment]
Thanks @marioba

**Comment by marioba** [comment]
Yes, the latest version of the plugin should solve synchronization problems that occurred with offline layers. @cocro, if you can, try to update the plugin and recreate the "portable project" to see if the problem is solved. Thank you.

**Comment by fegue** [comment]
I still have the same issue. Data points do not show up in the project after synchronization.
QGis: 3.4.7
QField: 1.0.3
QField Sync Plugin: 3.1.3 (or is it 1.0? I can't tell. Most current version)

For my colleagues with the same tablet and software versions, it does work however.

**Comment by qnmai** [comment]
I have what seems to be the same issue. Data attributes do not update. If one existing point's "ddate" field  (date type) and "dheure" field (time type) is completed, new points are added but attributes of existing points are not updated.

@3nids can you elaborate on the following issue and workaround/solution?

> I am just trying to be sure that the issue of date/time field was not interacting here too.
> Merge is about integrating the fix of date/time from the other pull request, and rebase means that this current pull request would have integrated this work.
> 
> But it should be good as is, since you were doing the things pretty well by not using any date/time field. Thanks again for your prompt testing and replying, as usual!

I have the same issue with:
QGIS 3.8
Qfield current (number tba)
Qfield sync: 3.1.3
Android tba

I have the following error in my QGIS log:
ERROR: invalid input syntax for type date: “”

I have done the following, without success:
-closed project by opening new project in qfield restarting tablet
-manually added "ddate" and "dheure" fields (date, time respectively; updated using trigger upon db update)
-updating "ddate" and "dheure" manually on one point resulted in all added points to synchronize (new points not synchronized before this step)
-[set fid column to hidden](https://github.com/opengisch/qfieldsync/issues/96)

**Comment by signedav** [comment]
Hi @qnmai
I tried to reproduce your issue but without success.
Can you try with the latest QField version and if the issue still appears provide us your project to test it?
Thanks.

**Comment by signedav** [comment]
Since I did not received a feedback and I belief this is solved meanwhile, I close this issue.
Feel free to reopen it, if it's still pending. Thanks :+1:

**Comment by qnmai** [comment]
Hello,

It has not yet been solved. I will send you our project this week. Excuse
me for the delayed response.

Best,
Nhu

**Comment by qnmai** [comment]
We have tried the newest version of qfield, and same issue.

**Comment by qnmai** [comment]
Hello, I've attached a copy of our project that causes the issue.
[SyncIssue_sgbd_fdpshp_TAB_190904.zip](https://github.com/opengisch/QField/files/3951955/SyncIssue_sgbd_fdpshp_TAB_190904.zip)

**Comment by saemiw** [comment]
...just a support note. We do have some synchronisation problems we don't understand completely yet. Our current guess is that it is linked to the date/time widget. Surprisingly it only affects some points.

**Comment by saemiw** [comment]
We do have some serious issues when synchronising data with QFieldSync. 
Using QField 1.2.0 some data are synchronised some are not. There is really no pattern with regard to the attributes or widgets used. 
Testing the same on QField 1.3.0 I noticed that WAL-files appear and I can't get rid of them, even if I close QField. When I copy all files (including WAL-files) on my computer, open and close the .qgis with QGIS the WAL files disappear. Subsequent synchronisation is then successfull. 

So my questions: 

- Has there been a change in WAL-file treatment from 1.2.0 to 1.3.0 (and even before)?

- Is it possible that 1.2.0 has some hidden WAL-files open that stock the data we're losing when synchronising?

- The WAL-Files are again apparent on 1.3.0 - could we get rid of them for good?

I am pretty sure that the here described problems are somehow linked to WAL-files.

**Comment by m-kuhn** [comment]
@saemiw the elimination of WAL files led to other problems (@signedav knows more I think) so we had to reintroduce them but data is now immediately synchronized from the WAL file to the main gpkg file and the WAL file was no longer dangerous in our tests.

So with 1.3.0 (in theory) all should be the same regardless if the WAL file is copied along or not. Did you experience any issues with respect to this?

With 1.2.0 we wouldn't be aware of any hidden WAL file presence.

**Comment by saemiw** [comment]
O.k. thanks for the explanations. 

With 1.2.0 we lose data (for no obsious reason). So "hidden" WAL-files could be an explanation.
With 1.3.0 I did not test dare to try the synchronisation at the presence of WAL-files. But I'll test...

**Comment by saemiw** [comment]
...ok. I lose data in two steps even. Firstly I lose some of the points when I delte/don't copy the wal-files from the tablet. And secondly a lose additional points when I do the synchronisation with QFieldSync. I made an ugly looking picture to explain:
![QField   WAL-files](https://user-images.githubusercontent.com/20398621/71014606-7e381300-20f2-11ea-83a1-0c012da2539c.png)

**Comment by saemiw** [comment]
> the elimination of WAL files led to other problems (@signedav knows more I think) so we had to reintroduce them

@m-kuhn: Do you know the last version without the re-introduction (just so I have a fast solution to our field workers).

**Comment by signedav** [comment]
I think last release has been 1.2.0. But we noticed there issues on digitizing.
How long the WAL files stay there on your device? The should be removed in miliseconds...

**Comment by saemiw** [comment]
ah no its not miliseconds otherwise I would not be able to copy the WAL-files from the tablet to my computer (I am fast, but not that fast ;D).

**Comment by signedav** [comment]
Yes you are right, they stay longer. Sorry, I noticed myself now.

**Comment by signedav** [comment]
But it's always empty (flushed after 500 ms)...

**Comment by m-kuhn** [comment]
@saemiw can you send us a set of  field files and the mother file?

**Comment by signedav** [comment]
> But it's always empty (flushed after 500 ms)...

Wrong again. Sometimes they contain data.

**Comment by m-kuhn** [comment]
That's serious! I'm glad we found it out before we pushed this to production.

Thanks for testing and reporting @saemiw (and please still send us the files)
@signedav can you have a look at this?

**Comment by saemiw** [comment]
Should 1.3.4 solve this issue (or the part with the wal-files at least)?

**Comment by m-kuhn** [comment]
The part with the wal files should be fixed (they are flushed into the main gpkg immediately after editing), the other part is still waiting for an analysis on what happens.

**Comment by saemiw** [comment]
o.k. great, can I do anything to speed up the second fix (testing...)? It is crucial for some of our projects....currently our only solution would be stay with qgis 2.18 instead of qgis3 (which is not something we really want).

**Comment by saemiw** [comment]
1.3.4 seems to solve the synchronising problems on android 9 tablets (Galaxy Tab Active2). Bravo.

On Android 5 tablets (Galaxy Tab Active) many of our projects that run smoothly on android 9 however crash (I'll open a different bug report). Also the performance is much slower. And on projects that don't crash, synrhonisation only works if all temporary files (WAL) are copied to the desktop computer before synchronising. It seems like the gpkg-flushing works differently/not on android 5. 

@m-kuhn Do you see an option to fix this for Android 5 as well in due time (we still have 25 of those old, well 3 year old, tablets)? Or are problems with Android 5 going to reappear and we should definitely move on to higher android versions.

**Comment by m-kuhn** [comment]
@saemiw I don't have any guess why Android 5 behaves differently the Android 9. They should all behave exactly the same. Is the performance specific to Android 5 or on both?

**Comment by saemiw** [comment]
> @saemiw I don't have any guess why Android 5 behaves differently the Android 9. They should all behave exactly the same. Is the performance specific to Android 5 or on both?

performance is worse on Android 5, but keep in mind that these are also older tablets (hardware).

**Comment by m-kuhn** [comment]
Thanks. Can you clarify the performance statement

1. The performance on Android 5 is worse than Android 9
1. The performance on Android 5 - 1.4 is worse than Android 5 - 1.2
1. The performance on Android 5 - 1.4 is worse than Android 9 - 1.2

**Comment by saemiw** [comment]
1. Yes (but as I said, maybe also linked to the hardware and not only the Android version)
2. Yes (if you mean with "1.4" "1.3.4")
3. No or at least not obviously...

**Comment by signedav** [comment]
Can we close this issue and open another one with the performance @saemiw ?

**Comment by Alain-LG** [comment]
I just realized that importing under Qfield with a postgres database does not work.

I have a project that is correctly exported and used on a android phone.
But when i import my files, the new records are inserted but not the updated fields of existing records.

I use QGIS 3.16.1 and QfieldSync 3.4.3.

Could you help me figure out how to correct this problem ?
