### ISSUE TITLE
Qgis does not sync with Qfield Cloud

### ISSUE THREAD

**Issue by mspoel80** [opengisch/QField#4508]
My projects, created in Qgis, then converted in to a Qfieldcloud project (with the plugin), does suddenly not sync back from the cloud after working on the project in Qfield on android. In the browser of Qfield Cloud i can see that the changes are synced, but in Qgis says that"project already synced and so does not retreve the changes. 

I can work around it by copying the files from the android device, but it worked normaly until last week. 

does anyone reconise this and/of have a solution? 

Hope anyone can help.

**Comment by Bvpraagh** [comment]
Not helpful as in a response but I do believe it is helpful to know others are having the same issue-  same thing happened top me last week. Had to use the work around. Today I cannot upload to cloud at all. Keep getting API error.

**Comment by SeqLaz** [comment]
To reapply the changes in QFieldCloud, please follow these steps:

1. Navigate to the project in QFieldCloud.
2. Go to the "Changes" section.
3. The changes will be listed in reverse order based on the time of the changes.
4. Find the first change in the list on the right-hand side.
5. In the "Action" column for that change, click on the dropdown list and select "Re-apply this and newer changes".
6. Finally, click on the "Save" button to ensure the changes are correctly reapplied and synchronized.

**Comment by Bvpraagh** [comment]
Thanks very much. I did try this at the time and it didn’t work. I ended up downloading each file separately in field and transferring them across to QGIS. I haven’t tried to upload to the cloud again as yet.

 

 

 

Dr Beverley Van Praagh

25 Jacaranda Place

Craigieburn

Vic  3064

 

Mob: 0402572443

**Comment by VxTedxV** [comment]
You should not leave publicly all these personal informations...
Just saying.

**Comment by mspoel80** [comment]
> 

Tnx. Edited.

**Comment by Bvpraagh** [comment]
> You should not leave publicly all these personal informations... Just saying.

thanks.  didn't see that.

**Comment by m-kuhn** [comment]
@mspoel80 is this still an issue for you?

**Comment by Bvpraagh** [comment]
To be honest I don’t know as I have been unable to upload a project to the cloud since this issue.

**Comment by m-kuhn** [comment]
Did you try to reach out to the support team? They should be sble to help you.

> For more quick assistance with this matter, we recommend reaching out to our dedicated support team. You can easily do so by clicking on the question mark located in the bottom right corner of the QFieldCloud platform. Our support team is always ready to provide you with the necessary help and guidance, please don't hesitate to reach out.

**Comment by Bvpraagh** [comment]
Thank you. I have finally been able to upload to the cloud but I honestly don’t know what the issue was. I think it was originally an issue with the Cloud e.g the API error. I am using a template that a developer did for me for Qfield with layers specific to my project (geopackages).

It is called “master” and is in my c drive. I open it in QGIS then add a new shape file with my new study area and then save it as a new project with new name in a different folder. I realise I have not always been saving it as a “package for qfield” which means the project QGIS file gets saved in the new folder but not all the layers. This may have caused some confusion. Anyway, for what ever reason when I was trying last week it all uploaded to the cloud for the first time in months. We are testing it today in the field so will see if we can sync it back to QGIS ok..

 

On issue I have which I assume is a bug is that everytime I open QGIS, I have to reinstall the Qfield plugins as the keep disappearing. I am using version 3.28. This may be beyond your remit!

 

Thanks for your help.

**Comment by m-kuhn** [comment]
Thank you very much for the feedback. Good to hear that the situation improved.
I assume this issue can be closed then. If you have troubles again, please reach out to [support](https://support.qfield.cloud/portal/en/newticket?departmentId=116946000000442061&layoutId=116946000000447348).

I unfortunately could not read, what keeps disappearing, so I cannot say if I can help.

**Comment by Bvpraagh** [comment]
Yes. Thank you.

**Comment by SeqLaz** [comment]
Thank you for your feedback,

I will proceed to close this issue, do not hesitate to contact to our [support ](https://support.qfield.cloud/portal/en/newticket?departmentId=116946000000442061&layoutId=116946000000447348) channel if have questions or need assistance,

Best regards.
