### ISSUE TITLE
Map rendering slower after recent update?

### ISSUE THREAD

**Issue by Wisarb** [opengisch/QField#4729]
### Describe the issue
Following a recent QField update, my Google satellite tiles and Drone GeoTif take significantly longer to render as you move around the map, it seems like Qfield now re-renders the entire screen every time you move the map? Instead of just rendering new tiles/pyramids that have come into view, the screen goes white and has to reload  the entire view? 

I'm not sure which update the change happened but it definitely used to be faster to look around the map. I spent some time working on the Geotif to get it to render in a couple seconds on Qfield. But now it takes about 10s to reload every time you move the map a tiny bit.

The Qfield project has not been updated through QField sync on desktop so the project should not have changed.

### Expected behavior
Google satellite and Geotiff load in a timely manner

### Observed behavior
Both Google satellite data link and locally saved GeoTif are much slower to load than before.

### Mobile
 - Device: Pixel 6A
 - OS: Android 13
 - QField version: 3.0.5 bfecdc

Additional information
Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliable reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

QFieldCloud: RHSWisleyArb RHS_W_Trees

**Comment by nirvn** [comment]
@Wisarb , can you share the problematic geotiff?

**Comment by nirvn** [comment]
@Wisarb , it'd be useful if you could dissect this a bit, e.g. is the slowness perceivable if you only show the XYZ google satellite layer? Or is that single layer noticeably slower to load too?

**Comment by monticola2** [comment]
I cannot provide any further details on this (@nirvn) but my projects also have been loading a lot slower since the update to v3.x.x. (I am on the latest release at the moment). Both loading the project as well as panning around the map (with mbtiles and tifs in background) takes I'd say about 1.5 to 2x the time it took compared to v2.8.7. Setting rendering quality to lowest helped a bit but is still much slower than before.

**Comment by nirvn** [comment]
@monticola2 , it'd be useful to investigate this further. E.g., do you see a slowdown when loading the sample bees project (which has not changed between 2.8.7) or not. If we can rule out some scenarios, it'd help figuring out what is happening here.

**Comment by monticola2** [comment]
The sample bees project is loading and panning quick in v3.0.6, no problems.

I have just reinstalled v2.8.7. My most problematic project had a load time of 25s with v3.0.6. compared to 12s with v2.8.7.
The project is too big to share here but maybe I can reproduce another project with the same culprit. Panning seemed no different though, it must have been in my head - sorry.
The project features a mixture of gpkg, plenty of tifs and some mbtiles that are arranged in quite a few folders in the layer tree and also feature quite a few map themes.

**Comment by nirvn** [comment]
@monticola2 , nice, so we now know the slowdown isn't generalized but triggered by something specific (project setting, dataset format, etc.)

It'd be of great help to the community if you could try to reduce your project into sample tests to identify the root cause of the slowdown. Suggestions:
- remove all map themes from the project, and try to see if that fixes the slow loading in 3.0 (you'll need testing on both 2.8 and 3.0)
- try creating mini projects containing only one dataset type (e.g. keep only mbtiles, keep only geotiffs, keep only geopackages), and see if you can identify which dataset type creates the slowdown.

It'll take you some time but would be of tremendous help.
