### ISSUE TITLE
Bad UX when navigating, if map has not finished refreshing

### ISSUE THREAD

**Issue by gnerred** [opengisch/QField#51]
When doing a pan or a zoom on a map that has finished refreshing, all is ok. When doing a pan or a zoom on a map that has not finished refreshing, the map tries to refresh before the pan or zoom is finished, and the view does not display the right objects at the right place. This is frquently the case, because map can take a relatively long time to refresh, as CPU performance on tablet is not so good if tablet is not very recent. A solution could be to stop trying to refresh the map when user begins to pan or zoom.

**Comment by m-kuhn** [comment]
This is a known issue.

At the moment we are using the QgsMapCanvas from desktop. It is the only
part that uses the QtWidget system and the qgis_gui library which brings
in a whole array of dependencies. Instead of fixing things on top of
this, it would be best to move to a system that works without qgis_gui.

This will also reduce the application size considerably.

**Comment by m-kuhn** [comment]
Should be fixed with 0.8
