### ISSUE TITLE
Forms Problems Qfield 3.2

### ISSUE THREAD

**Issue by denilsonjesus** [opengisch/QField#5145]
Simple forms that work in QGIS 3.36 and 3.34 are having problems in Qfield 3.2. The data, after being chosen, is changed with the change of choices in other fields. I have already done several tests and simulations and I was unable to solve it.

Follow link:

https://drive.google.com/drive/folders/10cnyXRJ9rcoK4kumpS85bfB-6YKOLKen?usp=sharing

**Comment by m-kuhn** [comment]
Thanks for reporting and the test dataset. Can you please add a bit more context that describes your exact problem?

**Comment by nirvn** [comment]
@denilsonjesus , this is what I'm seeing with QField 3.2.2:

![Screenshot_20240324-212028](https://github.com/opengisch/QField/assets/1728657/aa2b1733-d34e-43e4-9d3f-faa23c3127f1)

Everything looks quite normal to me. As @m-kuhn said, we'll need more information and context to help you out.

**Comment by denilsonjesus** [comment]
Hi, thank you for help me.

I'm sending the link again, with a PDF , a MP4 and the same Qfield project.

 tring to explain de problem.

https://drive.google.com/drive/folders/10o-9GFV0THzcA3OYY7aGwcSYiScWUAI8?usp=sharing


Denilson de Jesus
Celular:     (11) 96361-9745
________________________________
De: Mathieu Pellerin ***@***.***>
Enviado: domingo, 24 de março de 2024 11:21
Para: opengisch/QField ***@***.***>
Cc: denilsonjesus ***@***.***>; Mention ***@***.***>
Assunto: Re: [opengisch/QField] Forms Problems Qfield 3.2 (Issue #5145)


@denilsonjesus<https://github.com/denilsonjesus> , this is what I'm seeing with QField 3.2.2:

Screenshot_20240324-212028.png (view on web)<https://github.com/opengisch/QField/assets/1728657/aa2b1733-d34e-43e4-9d3f-faa23c3127f1>

Everything looks quite normal to me. As @m-kuhn<https://github.com/m-kuhn> said, we'll need more information and context to help you out.

**Comment by nirvn** [comment]
@denilsonjesus , OK, while QField behaves differently than QGIS, it actually isn't a problem with QField, and it reveals an issue with your configuration. 

Your value relation key column should give you *unique values*, otherwise the value relation widget will just pick the first matching key. In your configuration, you set your key to be "filter1", which is not unique, in fact based on your filter, all keys will be the same:

![image](https://github.com/opengisch/QField/assets/1728657/3dc7a68c-e11e-4599-865f-1292c63d77b5)

If you rely on a unique value such as "fid", you will find the widget to work flawlessly.

**Comment by nirvn** [comment]
@denilsonjesus , forgot to mention: you can witness your configuration also broken in QGIS. The id_fonte attribute will not 'stick' when you save your feature, it'll always go back to the first item in the list.
