### ISSUE TITLE
Network error 2

### ISSUE THREAD

**Issue by EgidijusViko** [opengisch/QField#5406]
Reopen the issue because last was closed by nothing changes. Please check again: 
Describe the issue
Problem appear when I connect to VPN. And try login to local it show "Address/api/network error" image added. From first expresion it looks like that some tokkens or what was cached, because after fully unistall application and install everything goes well again.

Reproduction steps

Go on connect to profile.
Download project.
Close app.
Wait ~30 minute or more.
Try again login
And show network error
image

Desktop (please complete the following information)
OS: [e.g. Windows]
QGIS Version [e.g. 3.22.0]
QFieldSync Version [e.g.4.0.0]
Mobile (please complete the following information)
Device: Android 13 Xioami
OS: [e.g. Android 11]
QField version: 3.20
Additional information
With older version it can't reproduce this problem but with 3.20 it started.

**Comment by suricactus** [comment]
Hello @EgidijusViko . Thanks for raising this issue again.

I am sorry to inform you that I am unable to reproduce your issue, and it seems the issue comes from your VPN provider. I have tested all of these with ProtonVPN with a server based in Latvia.

I downloaded a project from app.qfield.cloud to QField 3.3.4 on Android 14, created a point, and tracked a line. Waited for 30 mins and tried to push my changes. They went to the cloud successfully.

![Screenshot_20240630_113502.jpg](https://github.com/opengisch/QField/assets/2820439/1b1d1ec3-acf9-44db-83c3-e1f5c63888c4)

As I already mentioned, please send us an email at sales@qfield.cloud to discuss your issue in detail.

**Comment by joostvenema** [comment]
@EgidijusViko Just to let you, we're running into the same issue. We're also on a self-hosted instance of Qfieldcloud, but without VPN (actually we're only using a local network for synchronization).

**Comment by EgidijusViko** [comment]
@suricactus Please make note. That issue is releated with that exist cloud solution that why this issue was created?
