### ISSUE TITLE
Multiselection: Only possible to check N-1 options, not all N?

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QField#5611]
### Describe the issue
If there are 4 options (alternatives) in a value realtion allowing multiple selections set in QGIS, I'm only allowed to check 3 of them in QField. If N options, only N-1 may be checked in QField.

### Expected behavior
I want to be able to check ALL the options, not only N-1.

### Observed behavior
Not able to check all options.

### Screenshots and GIFs
QGIS: I may check all
![image](https://github.com/user-attachments/assets/0a7e18bf-68e0-4cf3-9621-26bc28dcae03)

QField: I can't check all
![image](https://github.com/user-attachments/assets/6565e73a-e95f-4594-94fd-b1c68f407996)

### QGIS (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.38.0
 - QFieldSync Version 4.10.1

### QField (please complete the following information)
 - Device: Samsung Galaxy Tab3 and an iPhone
 - OS: Android 14 and iOS
 - QField version: f59b22 v.3.3.11

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Don't know

**Comment by m-kuhn** [comment]
Thanks for reporting, could you attach a small sample project to reproduce this?

**Comment by 9ls1** [comment]
[lltreg.zip](https://github.com/user-attachments/files/16888509/lltreg.zip)
The multiselections are in the lltreg-layer.

**Comment by SeqLaz** [comment]
Hi @9ls1 

Thanks for the project attached,

After looking over your project and running a few tests, it seems the problem is with your **lltreg** layer. To fix this, you should remove the length limit on the "Value Relation" fields ( it's worth noting that when you use multiple selections, it creates a string like {1,2,3,4,5}. If you select all the Value Relations, the string can exceed your field's length limit).

I've also attached the updated project with the modified layers for you to test.

[lltreg_modified.zip](https://github.com/user-attachments/files/16900053/lltreg_modified.zip)

![image](https://github.com/user-attachments/assets/cf8738a6-0306-45d7-b482-bb4199d6672b)

**Comment by 9ls1** [comment]
Ah, I C (said the blind man). My mistake. When choosing both options for e.g. barkstruktur, I thought it would be saved 1,2 (=string with length 3). But it will be saved as **{**1,2**}** and hence string with length 5 will be needed. I'm using a python script to create the empty geopackage file with the layer lltreg (reading the attribute name and definition from a text file
```
navn;type;len;prec
treform;String;5;0
stammeform;String;5;0
barkstruktur;String;3;0
greinstruktur;String;3;0
kulturspor;String;9;0
habitat;String;7;0
...
```
and using `fields.append(QgsField(fname,set_variant(r[1]),'',l,p))` to create the layer. I will increase these "attributes-lengths" with 2.

**Comment by m-kuhn** [comment]
Basically QGIS could be better at communicating limitations 😅
