### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#59]
Writing down some ideas for the legend:
- Sidebar on the left (experiment with swipe, if the result is bad, add a button)
- Layer tree structured
- Legend for the layers
- Replaces the combobox for the currently edited layer
- Support for visibility presets (map themes)

**Comment by tethysgeco** [comment]
We’re beginning to use Qfield (great app!) and we think that a legend (similar to a table of content) could be very useful on site to visualize the meaning of layers in the map. Is it now possible? Thanks

**Comment by m-kuhn** [comment]
It is not yet possible (but should not be very hard to add).
See http://www.qfield.org/docs/development/index.html#make-it-grow-make-it-yours

**Comment by saemiw** [comment]
Proposition for an enhancement of the legend/table of content:
Instead of working with map themes (you can still keep this functionality of course...;D), it would be nicer to have the possiblity to check and uncheck individual layers (just like every one is used to on QGIS, other GIS-Software, google). Map themes also have the disadvantage that they need to be predefined (before field work) and is hence not very flexible in unpredicted situations.
