### ISSUE TITLE
Integrate with GeoGig

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#68]
It's the geo-version of git.
This means, concurrent editing with branches and conflict resolution.

There's a possibility to run geogig on a server and do a local checkout via REST api as geopackage. Changes can be pushed back via REST API as well.

Sounds like a very interesting approach to do hybrid editing!

http://geogig.org/

**Comment by biomap** [comment]
+100 if I could.  This would be great and extend the usage of Qfield a great deal imo. Other FOSS projects are integrating GeoGig and this would allow just what I was looking for.

## Additional info and Relevant Projects

### Other Projects with integration which you could use to sync include:

#### Geoserver
- [GeoServer GeoGig UI](http://geogig.org/docs/interaction/geoserver_ui.html)
because yay GeoServer  
- [GeoServer GeoGig Rest API](http://geogig.org/docs/interaction/geoserver_web-api.html)
- [GeoServer Resumable REST API](http://docs.geoserver.org/latest/en/user/community/rest-upload/index.html)
this may be useful for spotty wi-fi/cellular connections although I'm not sure of its integration with geogig

#### Geonode
- [Using GeoGig to load OSM Data into Manage OSM Data] (http://docs.geonode.org/en/master/tutorials/advanced/adv_data_mgmt/osm.html?highlight=geogig#using-geogig-to-load-osm-data-into-manage-osm-data)
- The Boundless Suite (if that's your thing) via the GeoServer/GeoNode as above.
- [GeoShape](https://github.com/ROGUE-JCTD/rogue_geonode) and [Arbiter](https://github.com/ROGUE-JCTD/Arbiter-Android)
this one has full integration into GeoNode within the application and was created a a full source solution by the developers of GeoGig.  It however requires a very custom setup of GeoNode which already requires a customized GeoServer (though they are moving to geofence soon) .  The [user interface and authorization chain](https://youtu.be/ZxfuRUg_s7w?t=10m38s) on this is great and could possible be reused with a little effort (I will have a look at it) and moved to a geonode/django extension.   Just a thought.

Looks like GeoGig has its own Web API, it would be nice if QField wasn't only able function via REST with and could work with vanilla geoserver/geonode or with a plugin for the intended app (say with the rest resume functions).

Just some thoughts.  Looking forward to it and thanks!   GeoPackage for tiles next??  :)

**Comment by m-kuhn** [comment]
> GeoPackage for tiles next

That's already in place ;)
http://www.qfield.org/doc/project-management/dataformat.html#raster-data

Rendering basemaps onto geopackage tiles from the QFieldSync plugin is on its way

**Comment by nirvn** [comment]
@m-kuhn , is this GeoGig project still alive / relevant these days? The project's github repository shows minimal activity.

**Comment by m-kuhn** [comment]
It would still be an open source candidate to adopt, but you are right it's not very active and I'm worried about adding java to the stack. Let's close this and reopen if it suddenly becomes a relevant option again.
