### ISSUE TITLE
gpkg_webp support

### ISSUE THREAD

**Issue by alexmodesto73** [opengisch/QField#684]
Is it possible to add geopackage raster support, in webp format ?

Because they save a lot of space

**Comment by m-kuhn** [comment]
Yes, it's possible. Someone will need to write a recipe for https://github.com/opengisch/OSGeo4A/

**Comment by rwjdennis** [comment]
I have just converted a large group of .tif to .gpkg using the GDAL library in OSGeo4W64 (I have also done .sid files to .mbtiles, but that's tangential). I think the .gpkg is very efficient, with the conversion from .tif to PNG_JPEG tiles resulting in 90% compression, more or less (120 MB to 12-13 MB). The problem I ran into with getting the tiles into .gpkg is writing the raster tables, but if the .tif files have the .aux files, you just have to specify that as the source of the raster table. I've pasted a .bat template below for the .tif to .gpkg conversion I used. Just specify the path and the EPSG.

 `for %%N in ([path]\*.tif) DO  gdal_translate --config OGR_SQLITE_SYNCHRONOUS OFF -co APPEND_SUBDATASET=YES -co RASTER_TABLE=%%N.tif.aux -co TILE_FORMAT=PNG_JPEG -a_srs EPSG:##### -of GPKG %%N [path]\%%~nN.gpkg`

With the WEBP support in GDAL 2.3, I think all you may need to do is change the 'TILE_FORMAT' value to WEBP in the above example. If I'm wrong, the documentation is pretty clear, otherwise (and I'm sure what I've provided isn't anything groundbreaking): https://gdal.org/drivers/raster/gpkg.html

**Comment by mbernasocchi** [comment]
@rwjdennis could you test the new WEBP support? 
I'll close this, please reopen if there are issues

**Comment by rwjdennis** [comment]
I will test this as soon as I can.
