### ISSUE TITLE
I want to change the Android code and make a new apk and use it. Attempted but failed. I need your help.

### ISSUE THREAD

**Issue by kieun84** [opengisch/QField#693]
Hello.
I am not good at English, but I need help.

I want to change Android code and use it.
Developed by Android Studio, the OS is Windows.

https://github.com/opengisch/QField
From the above address I downloaded and executed [android], but failed.
I didn't quite understand the [For Android] explanation here.
It seems that the Qfield SDK is needed to run on Android Studio.
Did I get it right?

It seems that you can get the QField SDK on Linux.
But I don't know Linux very well.
I want to get that SDK from Windows.
Is there a way?

If you don't have a way, Linux wants a detailed description of what to do.

I look forward to hearing from you.

**Comment by m-kuhn** [comment]
Hi,

Most code of QField is written in C++ and QML. Android Studio will not be of any (big) help for you to develop QField.

To develop on Windows, you will likely need to install Visual Studio Express and download all the dependencies from OSGeo4W. Nobody has built on Windows so far, so that's unexplored territory and requires a good understanding of build processes to get up and running.

To compile for Android, it's best to check https://doc.qt.io/qt-5/android-getting-started.html#windows

**Comment by m-kuhn** [comment]
Please continue this discussion on the [mailing list](http://lists.qfield.org/listinfo.cgi/users-qfield.org)
