### ISSUE TITLE
Horizontal and vertical accuracy field not fully visible

### ISSUE THREAD

**Issue by geomoes** [opengisch/QField#748]
on our Huawei M3 and M5 tablet (8.4'') we are running QField 1.2.0.
The display of the horizontal and vertical accuracy isn't fully visible, so that the corresponding data cannot be followed (see screenshot).

![Screenshot_20191221-182526](https://user-images.githubusercontent.com/30963421/71311511-bb1c4680-241f-11ea-8564-562a398f477f.png)

**Comment by nirvn** [comment]
It's on my to do list, lucky you ;) watch this space.

**Comment by nirvn** [comment]
@geomoes , a new three-column / three-row layout for the position information overlay has been added (see PR #677) for narrow screens. I'm not 100% sure your screen width would trigger the new layout, but it should make a fair amount of narrow screen users happy.

The other issue here has to do with the German translation, which has a much wider labels than its English counterpart due to the absence of abbreviations. The translation here should be considerate of the narrow space it lives in. "Hor. Genauigkeit" would be better :)

**Comment by m-kuhn** [comment]
@nirvn is this fixed now?

Actually the translation is already "H. Gen" and "V. Gen" thanks to @soester

**Comment by nirvn** [comment]
Yes, I consider this fixed @m-kuhn
