### ISSUE TITLE
diggitising point

### ISSUE THREAD

**Issue by sem-geologist** [opengisch/QField#77]
Hello,

I cant get point layer digitised,
 1) then activate digitise mode, and click the green pencil button, it  starts drawing the line instead of placing the point.
 2) if I click save it shows empty attribute filling dialog
What I am doing wrong. Qfield 0.8.3 is running on android 5.1 on the tablet.

I tested previously Qfield with 0.5 version and it worked.

It happens with all my project.
It also happens with projects there I converted everything to wgs84.

**Comment by m-kuhn** [comment]
Thanks for the report. Confirmed. Happens when there is only one single layer to digitize. Already fixed in the code. Update is scheduled.

On October 4, 2016 7:09:21 AM GMT+02:00, Petras Jokubauskas <notifications@github.com> wrote:
>Hello,
>
>I cant get point layer digitised,
>1) then activate digitise mode, and click the green pencil button, it 
>starts drawing the line instead of placing the point.
> 2) if I click save it shows empty attribute filling dialog
>What I am doing wrong. Qfield 0.8.3 is running on android 5.1 on the
>tablet.
>
>I tested previously Qfield with 0.5 version and it worked.
>
>It happens with all my project.
>It also happens with projects there I converted everything to wgs84.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/opengisch/QField/issues/77

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by m-kuhn** [comment]
Version 0.8.4 is released
