### ISSUE TITLE
 Vertical Accuracy doesn't show in QField (N/A)

### ISSUE THREAD

**Issue by ioioio25** [opengisch/QField#957]
![Example](https://user-images.githubusercontent.com/43608940/79610139-fd9c1a00-80c5-11ea-9386-0982c7223b6b.jpg)
Hi,
I'm using the latest QField version connected to a GPS device (EOS Arrow 200).
Is there anyone who knows why I can't get the **V accuracy**? (N/D) ...all the others values shown properly (X, Y, Altitude, Vit, H. accuracy)...

Thank you.

**Comment by rjwillson** [comment]
Hi Ioioio, 

I have also been using Eos Arrow devices (100, 200, Gold) to collect elevation data with QField and have observed the same behaviour, i.e., the vertical accuracy value is not visible when connected to the Arrow via Bluetooth and the VRMS value cannot be captured into a field the same way HRMS can. If you disconnect the Arrow and just use the tablet/phone's internal GNSS then the field can be populated. Therefore I wonder if the Eos Tools Pro app is outputing a modified code/ID in the NMEA string given that Eos Tools Pro is applying a true orthometric height correction. Possibly QField cannot recognize that modified code/output.

**Comment by ioioio25** [comment]
Hi Rob,
It is possible like you mentioned that EOS outputing a modified code/ID in the NMEA string given that Eos Tools Pro is applying a true orthometric height correction. I will check that with the EOS support service ...

**Comment by rjwillson** [comment]
great

**Comment by m-kuhn** [comment]
How has that continued? I'd be interested to know more.

F.Y.I.
We are currently also looking into opportunities to directly connect external antennas to QField (without mock provider) for better precision and quality integration, height correction, etc.

**Comment by ioioio25** [comment]
Hello everyonne,
I'm still waiting for a response from EOS GPS company...
Good news in regards to connect external antennas to Qfield. 
Please keep me up to date when available for testing ...

**Comment by rjwillson** [comment]
I have some great news on this. 

The team at Eos made some adjustments to their Eos Tools Pro software to push the V RMS accuracy value to the mock location and I have been doing some testing over the last few days with a beta version of Eos Tools they sent me with QField 1.5.3 and I can confirm that I can now see the vertical accuracy reported in QField and that a field set up in QField using @position_vertical_accuracy will populate the field with the correct value. The new version of Eos Tools hasn't been released yet but the developers have indicated that they are just working out a few bugs so it should be released soon

**Comment by ioioio25** [comment]
Wow, great news indeed!
I'll make some tests soon to see how is working.
Thanks for sharing with us Rob!

**Comment by eostech** [comment]
Hi guys, 

Correct, we are fixing this problem pretty soon with a brand new version of Eos Tools Pro. We are testing and validating beta version 1.50.13. We still have some bugs to fix with this version before we release it. 

Alvaro Paez
Product Manager
Eos Positioning Systems

**Comment by davdent** [comment]
Has this issue been fixed now?

**Comment by m-kuhn** [comment]
This has been an issue on EOS side of things (see https://github.com/opengisch/QField/issues/957#issuecomment-657561857)
Also a direct connection via NMEA is available now via bluetooth in QField, therefore bypassing mock location. Would be great if someone with the required hardware could verify this setup with an EOS antenna.

**Comment by eostech** [comment]
Hello,

Correct. With the new version of QField 1.9.6 and our latest version of Eos Tools Pro (2.0.0) this issue is fixed.

Here's a screen capture of Eos Tools Pro (Position tab) and QField (Map View) showing the values matching:

***@***.***D774A7.EFB891D0]  ***@***.***D774A7.EFB891D0]


Best regards,


[A picture containing person, drawing  Description automatically generated]
Alvaro Paez, Product Manager and Tech Support
Eos Positioning Systems, Inc.
TW<http://bit.ly/EosTW> | LinkedIn<http://bit.ly/EosLI> | FB<https://facebook.com/eosgnss/> | Insta<http://instagram.com/eos_gnss/> | YT<https://www.youtube.com/channel/UC7CiXt9VIDR0PO0xxMgJPhg/videos>
Email: ***@***.***
Office: +1 (450) 824-3325
Mobile: +1 (438) 825-5093

**Comment by eostech** [comment]
Confirmed.

When using Eos Tools Pro (with the mock location and Location Extras) and Qfield this issue is now solved.

Regards,


[A picture containing person, drawing  Description automatically generated]
Alvaro Paez, Product Manager and Tech Support
Eos Positioning Systems, Inc.
TW<http://bit.ly/EosTW> | LinkedIn<http://bit.ly/EosLI> | FB<https://facebook.com/eosgnss/> | Insta<http://instagram.com/eos_gnss/> | YT<https://www.youtube.com/channel/UC7CiXt9VIDR0PO0xxMgJPhg/videos>
Email: ***@***.***
Office: +1 (450) 824-3325
Mobile: +1 (438) 825-5093
