### ISSUE TITLE
Default Value doesn't calculate -  self referencing

### ISSUE THREAD

**Issue by ARBkey** [opengisch/QField#977]
Within my QGIS desktop project the following expression calculates as a default value of an real integer field

CASE 
WHEN "DBH" is not NULL and "DBH2" is NULL and "DBH3" is NULL and "DBH4" is NULL and "DBH5" is NULL then "DBH"
WHEN "DBH" is not NULL and "DBH2" is not NULL and "DBH3" is NULL and "DBH4" is NULL and "DBH5" is NULL then sqrt("DBH"  ^  2 + "DBH2"  ^ 2)
WHEN "DBH" is not NULL and "DBH2" is not NULL and "DBH3" is not NULL and "DBH4" is NULL and "DBH5" is NULL then sqrt("DBH"  ^  2 + "DBH2"  ^ 2 + "DBH3"  ^ 2)
WHEN "DBH" is not NULL and "DBH2" is not NULL and "DBH3" is not NULL and "DBH4" is not NULL and "DBH5" is NULL then sqrt("DBH"  ^  2 + "DBH2"  ^ 2 + "DBH3"  ^ 2 + "DBH4"  ^  2)
WHEN "DBH" is not NULL and "DBH2" is not NULL and "DBH3" is not NULL and "DBH4" is not NULL and "DBH5" is not NULL then sqrt("DBH"  ^  2 + "DBH2"  ^ 2 + "DBH3"  ^ 2 + "DBH4"  ^  2 + "DBH5"  ^ 2)
ELSE "DBH"
END

This does not work within QFIELD and just ends with Null value irregardless of the inputs. Does QFIELD not support CASE expressions? or am I missing something

**Comment by VxTedxV** [comment]
QGis version ? QField version ? Using Qfieldsync ?

**Comment by ARBkey** [comment]
QGIS version 3.12.0
QField 1.52
Not using QfieldSync. 

All other default value fields work within the same project.

**Comment by she-weeds** [comment]
Have you tried inserting the record (and getting the `NULL` value), then going back and updating the record (just change a value in any other field), and seeing if you still get a `NULL` value?

QField does not seem to automatically reflect default values upon insertion if it relies on calculation from another field, even though this now works in QGIS (see https://github.com/opengisch/QField/issues/914)

After update though it seems to work (if your calculated fields are set to Editable - otherwise there is a bit of a lag)

**Comment by ARBkey** [comment]
Hi Sheweeds,
Your prior report looks like the same issue. I will test if an update works this evening.
@m-kuhn and other Qfield Devs - Willing to put a quote together to implement this functionality?? 
Perhaps there would be a few willing to chip in.

**Comment by m-kuhn** [comment]
For the issue, can you reduce the example to a very simple `"DBH"` and check if this works. It's very likely related to using other fields within the default value expression (like mentioned in #914). This, to be sure that it's not specific to `CASE WHEN` but to the usage of fields in the default value.

For an offer, happy to do that, please contact info@opengis.ch

**Comment by she-weeds** [comment]
Default value update/calculation works in 1.7.6 if you use 'Fast Editing Mode' - you can instantly see changes in the data (and accompanying symbology) both when digitising and updating a feature  (see first part of gif)

There are some bugs in 1.7.7 and beta 1374 when digitising a new feature in this mode, so I won't recommend those just yet (see second part of gif)

However I'm also happy to say that in beta 1374 if you *don't* use fast editing, while it doesn't auto-calculate on the fly, once you've saved the feature it does finally calculate/run the expression properly, using values from that feature, instead of the previous one!

I will file a separate issue about fast editing mode, would love to see it function as it does in 1.7.6 because with the ability to save last value, search for species (!!!) and this, you truly have a wonder app! (Only last thing missing is buttons but that's a QGIS problem from what I understand.)

![QField_177_FastEditing](https://user-images.githubusercontent.com/41975056/101443790-503a8700-3972-11eb-9622-39c838ba8556.gif)

**Comment by nirvn** [comment]
This has been fixed in the latest QField 2.0 beta.
